### ISSUE TITLE
[Talk] alternative to plugins.enumerable_names

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [pyllyukko/user.js#101]
mozilla removed the `plugins.enumerable_names` leaving people's plugins list exposed but in this thread some solutions were found: https://github.com/dillbyrne/random-agent-spoofer/issues/283

a user created a userscript which can easily be a noscript surrogate instead https://github.com/dillbyrne/random-agent-spoofer/issues/283#issuecomment-172157842

`noscript.surrogate.noplugin.exceptions` = ` `
`noscript.surrogate.noplugin.replacement`=`Object.defineProperty(navigator, "plugins", {value: []});`
`noscript.surrogate.noplugin.sources`=`@^https?://`

this hides plugins from websites for noscript users. not sure if this is something to include in user.js but i hope people will find it useful

**Comment by CHEF-KOCH** [comment]
But this will break a lot, I'm not sure because all of this 'plugins' are evil thing. 

I mean seriously without detection some pages like YouTube/Video/Streaming pages couldn't identify the state of your installed plugins and will showing 'please install xyz'. I better prefer the (default) click to play method from NoScript instead.

EME and the plugin detection is also sandboxed, I saw this yesterday on a Mozilla page so I doubt that this is an good attacker/hacker point, especially it's known to not install any plugins or keep them up-2-date and pages rolling out more and more html5 (which then runs into canvas problem).

**Comment by berrythesoftwarecodeprogrammar** [comment]
it doesnt actually break anything though. i've yet to come across a website which relies on navigator.plugins to decide whether or not to show plugin content. plugins are also barely used these days. the most popular one is probably adobe flash and i havent seen a single flash website break with this hack. i dont think its used for anything except fingerprinting and thats what people are more worried about i think

and if one does ever stumble upon a website broken by navigator.plugins being empty, an exception can easily be added in `noscript.surrogate.noplugin.exceptions`. it accepts space separated domains e.g. `.youtube.com .videosite.com` :)

**Comment by CHEF-KOCH** [comment]
Nope, not true, we actually did break all plugins by using the wrong logic in our user.pref because we use click-to-play AND disabling plugins AND using NoScript (or recommend it). For me the better solution would be to let the user decide and remove click-to-play and the plugin stuff and let external plugins handle by NoScript. Navigator.plugins is also 'special' protected, see [here](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorPlugins/plugins) or better here which tells in the description that's [read-only](https://developer.mozilla.org/en-US/docs/Web/API/Plugin) so what possible attack we talking about? Right there is none. 

Btw I already tried to harden also NoScript stuff but the pull was rejected, so we may better mention it in the readme and let user decide (and of course it only needs to be done once since NoScript works well with Mozilla Sync [if enabled]).

As I said in other thread the 'fingerprint' hype should be slow down because it makes no sense to over and over say 'fingerprinting is evil' because standalone information can't reveal your entire surf behavior or identify. The exploits I saw also not care about fingerprinting they are more to get privileges to execute something.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
@CHEF-KOCH I am 100% sure that plugins can still be fingerprinted when not active and in click to play mode. I haven't tested disabled mode but probably. (I don't use user.js but I am reading into it to decide.) I wonder if there's some documentation kicking around here. I have many extensions that do things better without breaking them by disabling them like canvasing so yeah.. not related anyway.

Side note, some websites will default to html5 player if they cannot detect flash or ask you to install, but you can easily add exceptions for them. Porn sites are a good example.

**Comment by berrythesoftwarecodeprogrammar** [comment]
my method for hiding plugins works fine. ive only encountered 2 websites so far which i added exceptions for. you're right, most websites these days default to a html5 player or the built in firefox player now. flash is rarely needed to be enabled. and yes it can be detected while in click to play mode

**Comment by CHEF-KOCH** [comment]
*bumpedibump* :laughing: 

* https://groups.google.com/forum/#!topic/mozilla.dev.tech.plugins/_PsjN5SvZlo
* https://invis.io/H23WZEK35 (permission demo)
* https://bugzilla.mozilla.org/show_bug.cgi?id=1169945 (solved?)
* https://bugzilla.mozilla.org/show_bug.cgi?id=990808 (wontfix)
* Explanation -> http://forums.mozillazine.org/viewtopic.php?f=23&t=2965931 + TrackingList: https://wiki.mozilla.org/Security/Tracking_protection#Lists + https://blog.mozilla.org/futurereleases/2015/10/08/npapi-plugins-in-firefox/


After reading all this, I still not 100% sure if we need workarounds for this, especially if someone say it's still detectable??? I wonder how is this detectable if they want to kill PPAPI/NPAPI and maybe (as already written) plugins to replace them with a new API which should secure by default, or is there a problem with it's permission management I don't know about yet?

**Comment by berrythesoftwarecodeprogrammar** [comment]
its not about distrusting plugins, its about websites being able to fingerprint you by knowing every plugin you have on your browser. they are detected even if they are click to play. they are only hidden from the list if disabled. and there are more plugins than just flash. google talk plugins, adobe reader, silverlight, java, IETab. the majority of websites dont need to know that you have ANY of these installed. the websites which DO rely on these plugins most of the time use better methods to detect/activate the plugins than going through the list that this disables. the majority of flash sites DONT need to see this list to use flash

so hiding this list from websites by default and having a whitelist is certainly the best way to handle this list, unless one doesnt care about their plugin list being leaked. of course this is a personal preference, so i never intended it to be an addition to user.js. i just see many people asking for alternatives to plugins.enumerable_names so i want them to be able to see my working method. ill close it eventually, or let pyllyukko close it

panopticlick.eff.org result before noscript surrogate:
```
Plugin 0: Google Talk Plugin Video Renderer; Version 5.41.2.0; npo1d.dll; (Google Talk Plugin Video Renderer; application/o1d; o1d). Plugin 1: Google Talk Plugin; Version 5.41.2.0; npgoogletalk.dll; (Google voice and video chat; application/googletalk; googletalk). Plugin 2: IE Tab Plug-in; IE Tab 2 Plug-in for Mozilla/Firefox; npietab2.dll; (IE Tab 2 Plug-in; application/ietab2; ). Plugin 3: Shockwave Flash; Shockwave Flash 20.0 r0; NPSWF32_20_0_0_286.dll; (Adobe Flash movie; application/x-shockwave-flash; swf) (FutureSplash movie; application/futuresplash; spl). 
```
after:
```
undefined
```

of course it can also be modified to spoof plugin names or versions, whatever suits peoples preferences

**Comment by CHEF-KOCH** [comment]
* Why pages not need to know if you use plugins? 
* How they then detect if you have it installed or not to display there own content? 
* And do you think that the information panopticlick shows is relevant? 
* So you use xyz plugin in version, I see no data/security breach at all. 
* I did my own test by using the permission manager, it warns you about every access, the only what will be displayed is the versions number and nothing else and it also not loads anything. So please explain me why we need 'more' ?

![2t](https://cloud.githubusercontent.com/assets/727123/13193872/f06cadce-d780-11e5-956a-4338fdcc2986.png)
![2](https://cloud.githubusercontent.com/assets/727123/13193873/f07173b8-d780-11e5-930e-71138ea57c9e.png)
![3](https://cloud.githubusercontent.com/assets/727123/13193870/f067668e-d780-11e5-9fb8-3fbe0471e6df.png)
![4](https://cloud.githubusercontent.com/assets/727123/13193871/f06a1942-d780-11e5-9dc1-abfafb4a94b4.png)


So, everyone in the world knows know that I'm using Java in version xyz. Do you think this is metadata? This also could be easily revealed by social engineering because my email and my Android account are into Google Play Store public visible, so everyone can clearly see with a little bit brain that I use Java because I'm a developer. So again, what do you think is more critical that this isn't hidden from a page that I had never visited or should I had 'somehow' hide this meta information from Google by faking my own Developer account? And then? People still know that I'm using Java. 


This reminds me on the same discussion we already had with WebRTC and others, because it's there doesn't mean it's evil and because it's evil it doesn't mean everyone automatically compromises you somehow. And this is the reason why this was marked as wontfix because showing plugins or the versions doesn't mean it compromises your security, if if then an attacker wants to infect you because he see that you use an vulnerable Plugin/extension/addon whatever they need a lot of more steps. And if you getting infected just because this, this simply means there is something wrong in your security setup, maybe drive-by infection or something, and there is no spoofing/addon or something that can prevent this. 

Maybe we can once and for all stop this or getting a proof that showing such information makes you more vulnerable, there is nothing but just theoretically 'what if' things.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
@CHEF-KOCH specifically to your point, why give them an option? I'd rather not give them a slim chance something goes hokey pokey on my side or allow a website to have access to a piece of a bigger puzzle. We could debate panoptoclick until blue but the truth is, it was made because those things can be used. Is everything being used? Well, possibly not, but the trend suggests the more people blocking conventional methods the more they will use the unconventional methods.

Never forget that these companies spend millions if not more trying to exploit any seemingly benign feature for their own agenda. I see nothing wrong with an option to stop a browser from having loose lips that potentially sink ships. Not every plugin is like java in the way that it responds. (I presume this last bit.)

Opinions are divergent on this subject, however OP's goal is to inform people of alternatives to a preference that has been removed. (I would still be operating under the assumption that it worked if not for s/he.) For that I thank you @berrythesoftwarecodeprogrammar .

**Comment by CHEF-KOCH** [comment]
The thing is:
* All of this not preventing social engineering and you showed it yourself, without any HTTP/Screenshot you gave us the addon information. I also never heard that someone now would give this information from mouth to mouth just because security reasons. 
* Less tracking is always good but ask yourself, if everything is marked/labeled or knows as 'not works anymore' do you really think you won? I doubt the next stuff is coming then, like HSTS/WebRTC just as an reaction because everyone already know to avoid JavaScript/Cookies as much as possible.
* I agree and I already got your point, and I understand everyone want's to leave as less as possible footprints on the web without the necessary to reveal something especially to companies. But the web without ads wouldn't exist because no one or only few people want to pay for articles, or secure messaging, it's starts with Threema, ... what 2 Dollars .. to the hell why if I just can use WhatsApp for free ... you can argument like what you will also mention 100 other free messengers, they will just say ... 'but others using this'. Same like Facebook, so we have to deal with it, and hide as much as possible if we are 'forced' to use this.


You#re right with the Op thing, but it will not be merged because I already tried to harden and integrate NoScript stuff but the author not want it. And it's too complicated for normal users because it needs several other steps, especially if he use a lot or plugins or others which are maybe not explained in the possible given examples.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
Oh, no, I agree it is optional. 

I don't quite understand the first two paragraphs of your comment but... I would much prefer something that spoofs the information to be the most common average list, since firefox by default broadcasts this information to every website, if one user disables plugin announcements it could make them more unique, I believe that is also stated on panopto in generalized terms. 
 
But the same can be said obviously of obscure/less known plugins that get announced making a user unique. I think anything that finger printable browser information should be randomized and or spoofed to the highest average, that would be ideal. I will be keeping my eyes on this in the future in hopes that someone with more skill than I comes up with a better solution. This is more a stopgap measure.

**Comment by CHEF-KOCH** [comment]
There will never be a better solution, what be must understand that:
* Every protocol uses metadata 
* Hiding everything is (imho, as explained more or less) not an option especially optional things and 'wrongly' hardened settings may leak in security risks, holes or not prevent against that you accidentally give the information to others (e.g. via XSS, social e., Hardware or other attacks)

I realized that and that's why I not enabled everything in NoScript, RAS because the fingerprint now matter how small is still detectable, please [look at this example](https://github.com/Valve/fingerprintjs2) (even without blocking everything it displays an ID).

So the main question is to leave everything enabled and let FF 'fix it' by simply reporting it and get an discussion ground or you 'hide' yourself anyway behind a VPN and then most of them are useless anyway because it's faked/spoofed.

**Comment by berrythesoftwarecodeprogrammar** [comment]
you keep mentioning irrelevant things. there isnt any downside to blocking the plugin list from websites. you havent listed one real disadvantage

that site is also unable to fingerprint me properly

**Comment by CHEF-KOCH** [comment]
No? 
* Extensions if they use own fonts are almost unable to use
* Pages looking ugly 
* Tor uses a whitelist because no need to block everything (how about just disable javascript then the detection will never work?!)
* How about uBlock & front blocking which works better because you can work with per-site basis

The attack surface is very low because that requires to DOWNLOAD and get manipulated/infected font's there is no attack on system font's that coming pre-installed. The one and only font attack in FF (from 28 - 42) was already fixed in fact no one ever (officially) used that attack because that requires several other stuff to be executed.

**Comment by CHEF-KOCH** [comment]
There are downsites:
* If you block something pages always telling please install xyz addon which makes you more vulnerable because the change increases by factor 1000 that you get infected by drive-by because faked addons/plugins ...
* There is simply no benefit, I tested with Chrome in both modes, Incognito and normal ... almost the same, the only stuff they making better is to hide version information .. so what?
* We talking about metadata, this is critical as said the protocol itself is the problem 
* It's widely known that Mozilla/Google want to kill several stuff so I doubt we need this in the future, because HTML5/WebRTC and other things, and they are more dangerous
* Spoofing just the version number or entire plugin list would maybe something we could suggest to RAS so that everyone showing all plugins (even if he not use anything) - also lowers drive-by risk.
* Again, simply disabling javascript seems enough because the page can't load anything

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
@berrythesoftwarecodeprogrammar just wanted to update and say that exceptions for the noscript variant do not work. I will try your noscript variant. 

@CHEF-KOCH Mozilla and Google have given the clowns the key to the asylum and after much debate clown implementations have been made for user privacy. You're in clown town when you're using "protection" mode. Maybe if you wait a bit, the clowns will finish debating last years tracking mechanism and shake hands with other clowns like avalon. honk honk

In my opinion the users are more concerned about their privacy and the users drive the innovation because they are not mired down and beholden to a foundation or a company trying to make revenue. That's the great thing about the freedom to choose what you want when you want.

**Comment by CHEF-KOCH** [comment]
The best is still to simply not use any plugins, I think we all knowing this ... and if you really need to do it then better actually use Tor Browser or Chrome Browser since they are both known to be a little bit more secure due the nature of it's privacy policy aka sandbox/torbutton/and more... but I guess if we get e10s soon then this can be done in FF by just creating an separate profile for plugins for testing or whatever. If the stream is encrypted then it also plays no role also not with adobe flash, the attack scenario is more drive-by and not because requesting for .e.g stream which will be removed after it's loaded (just enable it within Flash settings or set the new limit).

I don't think Mozilla or Google helping clowns or implementing something which is a joke, the changes in the past year are very good especially for beginners because you simply can enable/disable it and then you are mostly good to go, it's not perfect I agree but more toggles or possibility's are not always good because they aren't fail-safe and harden everything from the beginning makes you more attractive and you possible suffer from my mentioned problems, especially on Facebook, YouTube and other popular pages - we not need to talk about that NSA/GHCQ are watching more such popular pages because the change to get something useful from such high bandwidth pages are always higher, but's an common 'problem' which never can be fixed, so need to talk about it. - but back to topic.

Since the OP not give an proof/confirmation how this is security relevant I think we should wait for Firefox e10s and an explanation how the tabs are isolated and from the memory protected because then we could talk about this again and I doubt that an attacker could easily escape or read-out something from the isolated storage without crashing the tab or the necessary to do additional steps.

**Comment by berrythesoftwarecodeprogrammar** [comment]
so the only real downside you mentioned is websites complaining that a plugin isnt installed, for which i said there is a whitelist that can be used, and that the majority of websites dont even rely on that list for plugin detection. e.g. the majority of flash using websites just load the flash or detect it through other methods instead of using that list.

its a personal preference thing. you can choose to use it or you can think it doesnt do much for you and rely on browser vendors etc to do everything for you

@L-a-n-g-o-l-i-e-r-s i havent tried the userscript, i only use my noscript surrogate and can confirm that the whitelist works. the spoofing however i haven't been able to figure out yet as i am not that experienced with that sort of javascript. but i'm sure it is possible. hopefully somebody can figure out how the Plugin and PluginArray objects work and be able to write a line which can spoof the list or modify the list. but for now, at least in my case, hiding the list from all websites and showing it to the merely *3* websites ive found which rely on it, has been a good solution

**Comment by CHEF-KOCH** [comment]
No there are other downsides, but you don't get it, you saying it can be detected anyway, I highly doubt that because it's only detectable via javascript, the rest is isolated. 

If you anyway use NoScript with 'correct' settings then your workaround is also not needed because you simply can work with permissions / whitelists and then all of mentioned things are irrelevant.

![restriction](https://cloud.githubusercontent.com/assets/727123/13205956/894b39a6-d8f4-11e5-8b11-fb74d81429ea.gif)


But I give up now, for me I made my statement, it's all explained and I simply not belive if we talking about metadata attacks that this is nessary because there are much easier way, simply disable javascript - end.

**Comment by pyllyukko** [comment]
@berrythesoftwarecodeprogrammar Thanks for this tip! I think we'll leave this trick out of the user.js itself, as I'd like to keep it mostly about Firefox's own stuff and not that much add-on related settings. But it's good to have it documented here.

Of course the best approach to all this would be to keep the count of installed add-ons in Firefox to minimum, so there wouldn't be that much to enumerate to begin with, but it's still good to be able to do this, as plugin/add-on enumeration indeed contributes to fingerprinting browsers.

**Comment by pyllyukko** [comment]
Related: [Bug 1281963 - Hide navigator.plugins and navigator.mimeTypes when resisting fingerprinting](https://bugzil.la/1281963) (from [#166](https://github.com/pyllyukko/user.js/issues/166#issuecomment-229253122))

**Comment by Roman-Nopantski** [comment]
Might make sense to note that 1281963 is still a work in progress

**Comment by Roman-Nopantski** [comment]
FYI: Flash when set to click to play now hidden from plugins + mimetypes
- https://www.fxsitecompat.com/en-CA/docs/2016/navigator-plugins-and-navigator-mimetypes-no-longer-list-flash-when-it-s-click-to-activate/
- https://bugzilla.mozilla.org/show_bug.cgi?id=1186948

**Comment by Thorin-Oakenpants** [comment]
This can probably also be closed @pyllyukko  - it's covered under resistFingerprinting

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
@berrythesoftwarecodeprogrammar 
Hello, 

jscher2000 or "Jefferson Scher" added mimeType protection see here: https://greasyfork.org/en/scripts/18256-hide-all-plugins If the link is down :8ball::

// ==UserScript==
// @name        Hide All Plugins
// @description Shows empty navigator.plugins and navigator.mimeTypes collections to selected websites
// @author      Jefferson "jscher2000" Scher
// @namespace   JeffersonScher
// @copyright   Copyright 2016 Jefferson Scher
// @license     BSD 3-clause
// @include     http://www.jeffersonscher.com/res/plugins.html
// @include     http://video.gazzetta.it/*
// @version     0.5
// @grant       none
// @run-at      document-start
// ==/UserScript==
// See: https://github.com/dillbyrne/random-agent-spoofer/issues/283#issuecomment-163059386 
Object.defineProperty(navigator, "plugins", {value: []});
Object.defineProperty(navigator, "mimeTypes", {value: []});

I copied the mimeType value from his script and edited your @berrythesoftwarecodeprogrammar  noscript surrogate to include mimeType: 

noscript.surrogate.nomimeTypes.exceptions = 
noscript.surrogate.nomimeTypes.replacement = Object.defineProperty(navigator, "mimeTypes", {value: []});
noscript.surrogate.noplugin.sources = @^https?://

noscript.surrogate.noplugin.exceptions =
noscript.surrogate.noplugin.replacement = Object.defineProperty(navigator, "plugins", {value: []});
noscript.surrogate.noplugin.sources = @^https?://

The NoScript surrogate way is the only way to get exceptions to work, exceptions will not work with the UserScript. I have tried. This is useful for folks whom don't want to enable privacy.resistFingerprinting because I have read it has caused problems in the past. (Unsure if this is still the case, I am also unsure if it included hiding/spoofing mimeTypes as part of privacy.resistFingerprinting's feature.)

I have no idea if webextension userscript managers are capable of changing these specific values any more, I'm using the last XUL/XPCOM GreaseMonkey, it can apply stuff to pretty much anything in the browser, using Waterfox here, at least for now. I'm also not sure if NoScript's surrogates for these values will have any effect as a webextension in the future, but I thought I would post this anyway. 🔎 🌵 😀 😅
