### ISSUE TITLE
Split up user.js

### ISSUE THREAD

**Issue by szepeviktor** [pyllyukko/user.js#103]
Please consider splitting up `user.js` to sections into `user.js.d` directory and add a build script:
`cat user.js.d/* > user.js`

**Comment by szepeviktor** [comment]
- 000-header.js               
- 001-html-apis-dom.js        
- 002-misc.js                 
- 003-extensions-plugins.js   
- 004-features-components.js  
- 005-automatic-connections.js
- 006-http.js                 
- 007-caching.js              
- 008-ui-related.js           
- 009-tls-http-ocsp.js        
- 010-ciphers.js

**Comment by CHEF-KOCH** [comment]
Why separate if we get the same into one file?

A lot of stuff is obsolete/deprecated I highly suggest (as mentioned in other threads) to remove this first instead of 'split' it.

**Comment by szepeviktor** [comment]
Actually I cannot see through one file but these section can be handles.
Now I examine all of the prefs and I decide keeping/changing them.

**Comment by CHEF-KOCH** [comment]
I don't see any benefit because according to you script you execute all of these settings it would make sense if you e.g. want to exclude obsolete ciphers settings (which are not needed anymore in latest FF releases). But in such cases we comment out some possible 'problematically' lines.

**Comment by szepeviktor** [comment]
Do you know Debian's `/etc/apt/sources.list.d/`? Its purpose is to keep the code clean.

**Comment by CHEF-KOCH** [comment]
APT isn't avl. for MAC/Win and this project should work for all not only Linux so. You can do the same with wget which is avl. for all OS to get latest user.js and place it automatically into your profiledir.

**Comment by szepeviktor** [comment]
Excuse me, I wasn't clear. The distributed files would stay the same, only the *development version* would be in `user.js.d`.

**Comment by pyllyukko** [comment]
> Please consider splitting up user.js to sections into user.js.d directory and add a build script:
> cat user.js.d/* > user.js

Somehow I feel it's easier to keep them all in one. At least when it's still reasonable sized. When it exceeds some 1000+ lines or something like that, it might be better to split it, but at this point I think it's better all in one.

Also it would be one more extra step to add changes to it :)

**Comment by CHEF-KOCH** [comment]
I only would suggest to remove as much as possible comments and better link into the threads (if present) or explain it into the wiki which would it make easier:

* Do Download/fork the documentation since wiki is forkable
* Reduce the size 
* Since no one or only few people reading documents/comments it would help to get an cleaner overview
* If it's documented in wiki you have more space to add warnings/notices (e.g. because obsolete settings) and such

**Comment by szepeviktor** [comment]
@CHEF-KOCH You can use UglifyJS.

**Comment by CHEF-KOCH** [comment]
@ szepeviktor 

Thanks for mention this.

I may star to use [your suggestion](https://github.com/pyllyukko/user.js/issues/103#issuecomment-172392112) as a ground for documentation now. Because I think this categories are not bad at all but personally I not want it for the user.pref.

**Comment by Hunter-Github** [comment]
I have a feeling user.js can be converted into a nice ansible playbook.

**Comment by CHEF-KOCH** [comment]
I did now the _basic_ work in the wiki, now we possible need to talk about improvements and which stuff is important. I speak e.g. aout to improve the table because I'm unsure what is the best to add to get an overview which isn't confusing for beginners but to really add the important information.

**Comment by pyllyukko** [comment]
> I did now the basic work in the wiki, now we possible need to talk about improvements and which stuff is important.

I think most of the stuff can be documented directly in the README. Some topics that are more cumbersome might benefit of having their own wiki page.

**Comment by CHEF-KOCH** [comment]
Problem is/was that it is a mess and newbies/beginners (I bet) never want to do the copy & past work. Now all is clickable, clean and you can see directly what is added per each category and see what of documentation is missing.

**Comment by szepeviktor** [comment]
@CHEF-KOCH Please see my proposed format: https://github.com/pyllyukko/user.js/wiki/Proposed-nicer-format
@pyllyukko Please delete it tomorrow.

**Comment by CHEF-KOCH** [comment]
Looks good, benefit is that each entry is link able. Problem with this is that with a lot of entry's (like in [Ciphers](https://github.com/pyllyukko/user.js/wiki/CIPHERS) you get almost the same mess as within user.js. I think the table isn't bad at all for a quicker overview but maybe an separate explanation to very important things could be added right under the table. 

I'm not really happy with it, I not found yet the correct/syntax/format, somehow I feel it also ends up (especially for beginners) with 'too much' input/information but I want to simplify that and not make it more complicated as in user.js file so that we get an cap between user.js and wiki to get the explanation over there instead of blowing up the user.js. 

Btw you can delete the page yourself, just click edit and then delete button.

**Comment by szepeviktor** [comment]
You can make an exception with Ciphers.

**Comment by CHEF-KOCH** [comment]
I made now [some test changes](https://github.com/pyllyukko/user.js/wiki/Extensions-&-Plugins), the first link icon is clickable (as test). The problem about that is that if I link directly into user.js then (in case of something changed) this would be inconsistent so I would need to work with revisions to ensure this exist all the time. 

Besides this I hope it's acceptable?
