### ISSUE TITLE
Font fingerprinting

### ISSUE THREAD

**Issue by publicarray** [pyllyukko/user.js#120]
I have found out that `browser.display.use_document_fonts` can be used to disable font fingerprinting. I have used it in my own user.js and have not found a problem with it. I recommend adding it to this project.

```js
// disable front fingerprinting
// test with http://www.browserleaks.com/fonts or https://panopticlick.eff.org
user_pref("browser.display.use_document_fonts", 0);
```

before:
![screen shot 2016-02-17 at 1 04 16 pm](https://cloud.githubusercontent.com/assets/5497998/13098825/e210b30c-d577-11e5-805e-cbbdd811e184.png)
after:
![screen shot 2016-02-17 at 1 05 06 pm](https://cloud.githubusercontent.com/assets/5497998/13098826/e43abf56-d577-11e5-9abd-c9155fdf00bd.png)

**Comment by Gitoffthelawn** [comment]
Does this require that every website download it's own fonts to the client or is there an equivalency matrix like with other technologies?

Also, this assumes Flash is allowed, correct?  To my knowledge, there is currently no way to prevent font fingerprinting when Flash is allowed.

**Comment by nodiscc** [comment]
@Gitoffthelawn it's not related to Flash (check the screenshot above, Flash is listed as not present), Javascript is used to detect fonts - https://www.browserleaks.com/fonts.

**Comment by CHEF-KOCH** [comment]
* Font fingerprinting can't be disabled 
* You can only '[reduce it](https://github.com/dillbyrne/random-agent-spoofer/issues/259)'
* Fingerprinting is not only that websites download the fonts
* Only internal Font's will be used for documents, but they are also detectable
* Entirely disallow all Font's on the OS level or browser [is critical](http://forums.mozillazine.org/viewtopic.php?f=5&p=14467379), it breaks (maybe) some apps/CSS

I highly suggest better to block it on OS level or [set it to audit](http://www.ghacks.net/2016/02/05/block-programs-from-loading-untrusted-fonts-in-windows-10/) under Linux it's also possible.

**Comment by CHEF-KOCH** [comment]
I'm not sure what's the best because on Windows and Linux you (even with this option set to 0) get detectable Font's (1/2 and the entire number of Font's) so I don't know if that is placebo or not, the question is how many pages sent e.g. on login this information along with other information which may then detect your or your real location.

**Comment by pyllyukko** [comment]
@publicarray: Thanks! I think this is a good idea. Also, the Tor Browser has similar feature not to use the system fonts.

**Comment by CHEF-KOCH** [comment]
You mark stuff as fixed which isn't fixable with about:config. ......

**Comment by pyllyukko** [comment]
> As said this is useless

I really don't think it's useless.

**Comment by CHEF-KOCH** [comment]
Tor uses a whitelist to 'solve' this to avoid e.g. problems with pdf.js. And I searched entire TorButton source and there is nothing ever mentioned that this is critical, the only stuff I found is that they totally block with NoScript every font (noscript.forbidFonts) + disabled the gfx pref (gfx.font_rendering.graphite.enabled). Then I did the test again and it still shows the font's based on the OS (on Windows 512) and on Linux it's controlled by [fonts.conf](https://bamsoftware.com/papers/fontfp.pdf). I tweaked all of this but it stil detect everything with a [real font test](https://www.bamsoftware.com/talks/fc15-fontfp/fontfp.html#demo), this is due text rendering itself. So, based on OS + 3/4 bits information which will be [sent into the http header](https://people.torproject.org/~dcf/fonttest.html) the attacker still knows anyway that you system minimum uses 512 fonts (e.g. in Windows). 

Entirely disable everything + disallow the download of it is not related that it isn't anymore detectable, so that's why I'm saying useless. I also think that is still possible to manipulate the page so that you get the fonts anyway even if you blocked the whitelisted ones by simply add an detection into the page which then shows an empty page and then you're forces to whitelist everything.

**Comment by CHEF-KOCH** [comment]
I suggest to mark this commit optional and refer to uBlock which got the ability to  block all font's or per-site basis.

**Comment by pyllyukko** [comment]
So a step forward is useless, if you don't get into the destination? Even the [site you linked](https://www.bamsoftware.com/talks/fc15-fontfp/fontfp.html#summary) (thanks for these links BTW.) states "Fingerprinters have to work harder for worse results—that’s good!", which is on the spot. We'll never have everything perfectly secure and private, but it's all about raising the bar.

And even though different add-ons handle some of these things, it's always better to try to do it from within Firefox itself. Besides, there's really no guarantee that all the users use all the add-ons we recommend, so again, it's a step forward.

But yes, definitely not an absolute fix for this issue, but improvement nevertheless.

**Comment by publicarray** [comment]
@CHEF-KOCH Thanks for all of the research. I agree that it's not a perfect solution but it does prevent simple js enumeration like [this test](http://www.lalit.org/lab/javascript-css-font-detect/).

uBlock Origin blocks network requests and does not prevent font fingerprinting at all. It can be used to reduce the number of hostnames you are connecting to. e.g. you can block 3rd party fonts.

**Comment by berrythesoftwarecodeprogrammar** [comment]
i wish there were an option to disable only detection/use of local fonts so that remote fonts could still be used. that way websites with custom fonts could still be seen properly (and also controlled via addons like ublock). this breaks custom fonts on everything including certain addons. and it probably makes you stick out in a way since most peoples fonts are enumerable. but it might be better than leaking the whole list

**Comment by publicarray** [comment]
I have used this setting for such a long time that I've probably forgotten how the web looks like with custom fonts... 

![screen shot 2016-02-18 at 5 24 47 pm](https://cloud.githubusercontent.com/assets/5497998/13136385/d07464a2-d664-11e5-97f5-4b0ae2331794.png)
http://www.w3schools.com/cssref/css_websafe_fonts.asp

Sorry I have forgotten that the fonts are indeed not loaded.

**Comment by CHEF-KOCH** [comment]
Maybe we can re-open this because it isn't fully answered/fixed and there are problems especially on CSS. I tried to test Tor Browser and it looks 'better' (because whitelist) so our option to only use the OS/Browser related are not what I expect especially because no one (including me) can provide the relationship between font's and attacks or fingerprints and how is that important because otherwise we not need to block this in general. 

As I already said uBlock would be an option but as publicarry correctly mentioned it just reduce the domains/hosts it wont's the fon't loaded from. Imho this is still a better solution because you can disallow/allow this also per-site basis (click the little buttons on the bottom to toggle it).

**Comment by Gitoffthelawn** [comment]
@publicarray @nodiscc @CHEF-KOCH 

My apologies.  In my post, I wrote, "Also, this assumes Flash is allowed, correct? To my knowledge, there is currently no way to prevent font fingerprinting when Flash is allowed."

I meant to write: "Also, this assumes Flash is _**NOT**_ allowed, correct? To my knowledge, there is currently no way to prevent font fingerprinting when Flash is allowed."

Brain going faster than my fingers! :-)

**Comment by CHEF-KOCH** [comment]
Correct there is no way because in case Flash placed his cookie the information could directly grab from there together with the 3/4 bits send along with http header. Maybe to fake the header and disallow cookies could reduce this but I think it would break then the page or some functions.

**Comment by Atavic** [comment]
[Fluxfonts](https://ctrl.blog/entry/fluxfonts): font fingerprint cloaking.
I ilke this obfuscation idea: https://github.com/da2x/fluxfonts
https://github.com/pyllyukko/user.js/issues/189
https://github.com/ghacksuserjs/ghacks-user.js/issues/34

**Comment by Albirew** [comment]
This post is mainly meant for people trying to find why they have icons replaced by text in some webpages.

For the CSS downsides of this setting, here are some examples (android download page where tickbox has been replaced by text and TinyTinyRSS page where icons has been also replaced by text.  Both use "Material Icons" font)
![screenshot](https://user-images.githubusercontent.com/2805161/54017460-02319780-417e-11e9-8b23-f65b4803df09.png)
