### ISSUE TITLE
DNS servers

### ISSUE THREAD

**Issue by MacProGirl** [pyllyukko/user.js#124]
I don't know if this is very off topic or if I may ask, 

Is it important to change DNS servers? For security and performance.

At the moment I am using my network provider's default DNS servers.

**Comment by pyllyukko** [comment]
Well it really depends on what you're trying to protect yourself from. Of course the DNS provider always knows and can track who queries what. It's also a matter of who you trust. Do you think your ISP tracks DNS requests and profiles people/customers according to that? For instance, I would never use Google's DNS servers, because they hog all the data that people might provide them with.

You can hide your DNS traffic from your ISP for instance by using some VPN, but then the VPN provider knows this. So again, who do you trust?

You can also use [Tor](https://www.torproject.org/) for DNS, but then the exit nodes can spoof the responses (as [DNSSEC](https://en.wikipedia.org/wiki/Domain_Name_System_Security_Extensions) is not that common yet). Again, do you trust Tor more than the ISP or some VPN provider.

It's always a trade-off.

Maybe some other user.js users can also provide tips with some alternative DNS providers/technologies.

**Comment by uberspot** [comment]
You can setup dnscrypt if you don't want your dns queries to leak and are afraid of MitM https://dnscrypt.org/
It's not perfect but it is an extra protection.

**Comment by CHEF-KOCH** [comment]
It's not important because if you change the DNS to another one then this means you must trust them. But in some environments this could make sense, if you want to bypass some ISP restrictions (e.g. in China/Office/...)-

> DNSSEC is not that common yet

Disagree, Google by default uses DNSSEC and many bigger ones too I would sy it's common but DNSSEC also suffers from [several attacks](https://en.wikipedia.org/wiki/Domain_Name_System_Security_Extensions).

Performance wise it's difficult because several extensions requires more bandwidth for the checks they do. On e.g. Dnscrypt you can disable (if your/server not supports it disable IPv6 via a plugin) So if you prefer security you simply have to life with some performance drops because the upstream resolver may need some 'extra rounds' which coasts time. Gaming on a security based system is not really good because you usually get a bit higher ping. 

On my system I use DNSCrypt + Unbound (as Cache) and disable entirely the OS DNS system. It works on all systems Win/Linux but may require some time because you need to change some configuration things.

I not recommend to use Tor for DNS because performance, you simply can't do e.g. I2P because it's pain and several other things which is also mentioned on there own wiki.

It's up to you what you prefer.

**Comment by berrythesoftwarecodeprogrammar** [comment]
dnscrypt is definitely worth it for security and not hard to use once you figure it out

**Comment by MacProGirl** [comment]
I don't really have any online activities that I need to hide. So this is not a big concern I guess. The performance factor is more important. 

I am running on Mac OS X and my Time Capsule works as a router so that is where I will do the DNS changes if that is any help. I am also located in Sweden if that is a factor when choosing DNS server.

**Comment by berrythesoftwarecodeprogrammar** [comment]
well people on your local network may be able to pretty much figure out what youre doing and what websites you are visiting, and your ISP and others definitely can, with regular DNS. there are a few swedish DNSCrypt servers, it doesn't affect performance that much to use it

**Comment by pyllyukko** [comment]
> I don't really have any online activities that I need to hide. So this is not a big concern I guess. The performance factor is more important.

Just remember, that we still should have the right for privacy :) See: <https://en.wikipedia.org/wiki/Nothing_to_hide_argument>

> I am also located in Sweden if that is a factor when choosing DNS server.

If you live in Sweden, the [FRA](https://en.wikipedia.org/wiki/National_Defence_Radio_Establishment) is indeed watching all the traffic.

**Comment by CHEF-KOCH** [comment]
Please close off-topic.

**Comment by pyllyukko** [comment]
Might be a bit off-topic, but it's always good that people are interested about their security/privacy and are not afraid to ask questions.

@MacProGirl: Hope we answered your question.
