### ISSUE TITLE
Disable WebIDE?

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#142]
See https://github.com/amq/firefox-debloat/pull/24/files

Does it make sense disabling the Web IDE in this user.js? (I think yes. It is likely not in use for most users and increases attack surface)

**Comment by CHEF-KOCH** [comment]
No it makes no sense, I already talked about it. I asked if it would make sense to entirely disable all webdev.* entries because it may could be used to backtrack you by using remove debuggers. But this in fact would require you need to execute the script under highest privileges. Today's OS not allow this without any notifications, so it's more a theoretically hack. 

I also doubt that if safebrowsing/disconnect filter list is in usage this will spread much around the world, each page which is monitored and in the index of google will now be automatically warned about insecure stuff, it's up to the webmaster to decide to keep this or not, otherwise you see a warning. The thing is that we disabled it here and I'm unsure if that is perfect, on one site any AV today sending much more stuff back as googles safebrowsing, on the other side I think it's still tracking since Google now any page you visit. 

Overall I think if you disable entirely the remove debugger as we already di this have no effect, same like safebrowsing.

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH Just a correction: I don't think there are any settings in Firefox that send every page visited to Google.

If Google Safebrowsing is enabled, it definitely does periodically send some information to Google: IP address, browser, browser version, OS version, other UA string information, other header information.

Also if the file detection "feature" of Google's Safebrowsing is enabled, it also sends Google a hash of some of the files the user downloads.

**Comment by CHEF-KOCH** [comment]
Well, your right I was not detailed enough. Of course this is what Firefox [sends back](https://www.mozilla.org/en-US/privacy/firefox/), it not mentioned any 'web.*' related stuff, so from my understandings it's more theoretically because you definitively need additional steps to compromise your browser security.

**Comment by toogley** [comment]
would disabling  the webide increase the performance/responsiveness of firefox?

**Comment by CHEF-KOCH** [comment]
No since it's only loaded when you use it. It's not loaded by default in background.

**Comment by pyllyukko** [comment]
> Does it make sense disabling the Web IDE in this user.js? (I think yes. It is likely not in use for most users and increases attack surface)

Hmm. Not sure. This WebIDE stuff seems to relate more to Firefox OS. I already disabled some Firefox (the browser) remote debuggin stuff with 9715f3cc7e85da807f3872bb29d2bbc79615387f & 4798bf855ca9f243f0b74c077bd3a896a10c213c though.

**Comment by Gitoffthelawn** [comment]
@pyllyukko It's only related in that Google was brought into the discussion in regards to some questionable default features integrated by Mozilla into Firefox.

**Comment by nodiscc** [comment]
> How exactly this WebIDE relates to Google?

I did not understand why this was brought up either. I guess it's unrelated.

> We have the tendency of disabling unneeded features, so in that sense yes.

My point exactly.

**Comment by pyllyukko** [comment]
Done. Thanks, @nodiscc.
