### ISSUE TITLE
Another fingerprinting test

### ISSUE THREAD

**Issue by publicarray** [pyllyukko/user.js#145]
https://audiofingerprint.openwpm.com/ 🔈

**Comment by CHEF-KOCH** [comment]
Bump: https://gist.github.com/CHEF-KOCH/29510713e9a2c8bd52d84ac761678a55

**Comment by nodiscc** [comment]
ajax.googleapis.com can also be avoided by using https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/ - https://github.com/Synzvato/decentraleyes - A Firefox add-on that emulates Content Delivery Networks (CDNs) locally by intercepting requests, finding the required resource and injecting it into the environment.

**Comment by CHEF-KOCH** [comment]
Is it really necessary if we use NoScript? I doubt. Googleajax should in my opinion never blocked it breaks too much. According to the GitHub page (which I starred long time ago) it still have huge problems. Since it's not really a 'final' product I consider to not suggest it in this stage. Since it simply could more dangerous than it helps (currently). 

But I'm not into the addon to come to an final conclusion, last time I chat with the developer he said it's 'beta' and a lot is on the todo.

**Comment by nodiscc** [comment]
> Is it really necessary if we use NoScript?

Nope. But in some instances when using NoScript or other Js blocking solutions, you have to whitelist a CDN when a page requires it to interact with basic functionality (for example stackexchange websites require googleapis for anything except simple logged-out browsing).

> I doubt someone really can hack or abuse any Google service since they are constantly evolved and under active development,

> I doubt someone really can hack 

Better safe than sorry. In case of a MitM attack on `ajax.googleapis.com` the attacker would have the ability to inject custom javascript in pages (_if_ the CDN has been whitelisted). Layered security. `ajax.googleapis.com` is only authenticated using TLS, which has been proved vulnerable in the past :)

I agree that Decentraleyes is still in beta. Whether we should wait to recommend it or not, I don't know. user.js already has some "experimental" (and sometimes breaking) settings, so why not. It works fine for me.

**Comment by publicarray** [comment]
If you like to learn more I suggest to give the research paper by the Princeton University a read: http://randomwalker.info/publications/OpenWPM_1_million_site_tracking_measurement.pdf
or the corresponding website https://webtransparency.cs.princeton.edu/webcensus/index.html.

**Comment by Ileca** [comment]
Since I am using user.js, I always wondered why it is not enforcing the strict list of the tracking protection but I guess it's because it breaks usability too much?
Like nodiscc said, because of google CDN used for hosting jQuery broking a lot of important features (arf, yes, stackexchange nebula, I asked them if they could use the Jquery CDN but they didn't answer so I guess they prefer their users to be tracked than losing perf), this extension should be better than my crappy resources reallocating user-script which work half the time. >.>
If someone can enlighten me with another good customizable add-on (or something else) that can redirect resources (or do html replacement) AND work with the new WebExtensions, I would appreciate.

It's a matter of opinion but I think that allowing something like the almighty google CDN is defeating the purpose of that user.js even if you are forced to find hacks.

Btw, like we are talking about CDN and Disconnect, isn't that weird that Disconnect's filters in Ublock are hosted by amazonaws? I mean, Amazon!

**Comment by CHEF-KOCH** [comment]
I think the entire CDN stuff is more theoretically, it can't be hacked directly as mentioned it often gets updates which makes it impossible. I think we talking about pages which uses vulnerable addons/extension/whatever for the board software which requires googleapis and ajax to work, which is then only vulnerable if you directly attack the board software, this means the software must be vulnerable + the admin of the page uses outdated products, since wordpress and any other cms regularly gets updates. If you ever worked with it you know you get an big warning that there is an security update avbl. 

I think faking this is not really possible, since you will break stuff, for sure. As an result we got already HSTS and at some point we should maybe stop it, because we just get more and more tracking instead of less because we trying to block something on Browser level instead of to not allow them by default within the browser source. I think Chome is here better because you simply can work with -flags to disable on Browser Source what you not like like e.g. WebRTC, but again at some point it's even deeper HSTS is an legit method directly implemented on OSI level 4 so to block this may break again other stuff. I think NoScript is already enough since you simply can add whitelists which is imho enough, the temporary whitelist get's destroyed after you close the tab/page . I think it's the best you can do, because otherwise you globally allow it or simply block everything which annoys me and other people. 

Disconnect filter list is not anymore necessary in any addon since Firefox integrated it directly, if you use the stronger list it also breaks certain pages. 

But back to topic this is just only about audio fingerprinting, not more and not less, it's not new and theoretically some pages could detect you via CPU/Mainboard directly, of course all of this would require to allow the page to abuse low level API's which are generally not our fault, it must simply disallowed within the Browser so that the webmaster are forced to use alternatives otherwise the web will never change and we not need more and more addons it's enough.

**Comment by pyllyukko** [comment]
> Since I am using user.js, I always wondered why it is not enforcing the strict list of the tracking protection but I guess it's because it breaks usability too much?

Well the real reason is, that I couldn't figure out a way to change this in ```user.js```. It seems to work a bit differently. It is [documented in the README](https://github.com/pyllyukko/user.js#this-is-not-enough) though. But... it does indeed break a lot of sites, so it's better to leave it for the user in that sense also.

**Comment by pyllyukko** [comment]
Regarding Decentraleyes:

> @pyllyukko I think you might want to add this addon to the recommended list.

Please open a separate issue so we can discuss this. I haven't used this add-on, so I have zero knowledge about it, so I can't add it straight away.

**Comment by CHEF-KOCH** [comment]
Can be add in readme or Contribute to provide minimum any examples if we talking about 'break' something, it's impossible to verify something without anything. I think we hit now an stage which needs minimum an page + on which OS + which browser.

Otherwise it's not helpful to say xyz will be broken 'IF' ... 

Audiofingerprinting is also missleading term, because acustic (audio) itself [does not fingerprint](https://en.wikipedia.org/wiki/Acoustic_fingerprint).

3th-party fingerprinting becomes more and more the common solution to detect you, but I see no problem to general block every external resource and only allow them if it's really secure and necessary.

**Comment by CHEF-KOCH** [comment]
It's no possible that an CDn tracks you by an owner, this requires huge effort and someone would notice that since you get other timings. High bandwidth domains which mostly using CDN's are compromised in other ways, they can grab directly the cables to duplicate the traffic which is not detectable, like NSA/GHCQ already did on several 'internet nodes. 

Detect uBlock have nothing much to do with CDN's because you can simply use jQuery, Javascript, AdSense (via Javascript) itself which needs to be allowed by NoScript. Example is explained over [here](http://w3guy.com/detecting-adblock/) or if you want code [here](https://github.com/sitexw/FuckAdBlock). Again this is mostly via javascript and nothing else. Ghostery is not closed source but I said I not got any access to download the source (you can still browse manually). 

If the Browser simply not support some java api's no one could use any tracking since it would result in wrong results, TorButton/Tor Browser does this by faking e.g. the client so that everything use the same 'client'. You simply can't fake something if you need the network, google luck using facebook without fbcdn. Maybe you not understand the difference but if you fake them, you simply break stuff. An good example is if you use html5 fake everything and want to play 5.1 sound and you may not get 5.1 because you faked the api to think it's only 2.1. uMatrix also blocks and not fake something. Same like uBlock. As said you can't fake much if Googles CDN almost gets weekly updates because the tools you use are behind (always) and blocking them directly in the source would force the webmaster to use only Mozilla's/Googles 'trusted' API's which are not dangerous.

**Comment by CHEF-KOCH** [comment]
We may could use and clean this thread to submit fingerprint pages, instead of opening 100 million issue ticket for each new.

I start, another Tor fingerprint test:
https://tor.triop.se/ 

it not even fingerprints Tor, it's mostly designed for it but it also detects if you're on Tor and also adds an unique ID to show something. The [code is directly available on GitHub](https://github.com/jonaslejon/tor-fingerprint/).

**Comment by nodiscc** [comment]
> We may could use and clean this thread to submit fingerprint pages

1 issue/PR for each test. Crawling through comments is a waste of time.

**Comment by Gitoffthelawn** [comment]
I shared this fingerprinting test (https://audiofingerprint.openwpm.com/) with several colleagues, but I received some negative responses because there is no option to opt-out of them "collect[ing] the fingerprint along with a randomly assigned identifier, your IP Address, and your User-Agent and store it in a private database".  As we all know, there is no such thing as a private database, especially in the USA where that test is located.

Is there a similar online test that does not store data (I could have people host it themselves, but that is too much work for many)?

Similarly is there a test I can share with others that just reports Canvas, Javascript, and Flash Font Detection without storing any data?

**Comment by CHEF-KOCH** [comment]
It's difficult because you can't look behind. Even if the test itself not collect anything the entire domain may collects several information such as IP, Mac (mostly due IPv6) address, several Headers and maybe more. 

I'm unsure if something exist which not log something, [because this requires a new backend](https://www.technologyreview.com/s/601488/largest-study-of-online-tracking-proves-google-really-is-watching-us-all/) (since every page with an proper CMS integrate some logging to protect e.g. against DOS attacks). But you speak about the database itself and if they may use it for selling it and other things - I'm unsure. Ghostery is one example (maybe). 

An good start could be that an page plays some audio and then you simply get the hash back, explained over [here](http://www.codeproject.com/Articles/206507/Duplicates-detector-via-audio-fingerprinting).

I doubt that there will be alternative pages, this hole never worked in Chrome and possible (if affected) will be closed soon on Firefox too. I think we already talked about that one page or one test not helps to detect you, as always it's not the entire cake, just one piece of it. I more would have the fear that someone create a fake 'test' page.

I think a start for you would be to discuss this maybe over [here](https://github.com/brave/browser-laptop/issues/242). But fingerprintjs2 is the only solution here on GitHub which comes to my mind.

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH I agree with everything you said.  Yes, any server may keep logs, but most sites just keep them for diagnostics and then delete them after 1-30 days.  But that one explicitly states that they collect multiple pieces of data and maintain that data in a database.  It doesn't sound like they ever delete any of the data.  It's probably not even encrypted.

So I'm just wondering if there are other sites that run the same tests, but don't collect data.  Of course, they *could*, but that's at least a step better than knowing they do.

I'm interested in both the audio tests and the Canvas, Javascript, and Flash font detection.  No problem if it takes a combination of 2 or more sites.

**Comment by CHEF-KOCH** [comment]
I see that not that critical, the difference is only maybe if the page mention what they collect /the given page also says exactly what they collect) - a good example is the EFF test, because it shows and mention the [things visible](https://panopticlick.eff.org/privacy) BEFORE they collect something (of course difficutl to proof for the 'normal' user) but this is then more a part of the Browser to help the User in such a case (e.g. ssl/tls warnings, cookie icon and more ...)

[I created now a little page](https://github.com/CHEF-KOCH/Online-Privacy-Test-Resource-List) myself (it will [get git-gh](https://help.github.com/articles/creating-project-pages-manually/) support soon) which may list all test pages with a warning or something which gives the developer of the page a chance to react and may fix this or mention it but from what I see you already found my project. If I find new and good pages I will add them, for sure. :+1:

**Comment by nodiscc** [comment]
So what should we do about this? Add the fingerprinting test to the README? Or can this issue be closed

**Comment by CHEF-KOCH** [comment]
I already submitted a pull but as mentioned we could use this thread in general for submitting pages which may detect such things.

The con is what you've said, it's maybe not that easy to scroll trough the comments. I'm unsure, if it's better to submit each stuff at it's own then we can close it. It's up to the project creator. :unamused:

**Comment by pyllyukko** [comment]
It's there now: 35cde05c15561d5c6a1d16c7d8494eb3a08df204

**Comment by pyllyukko** [comment]
Thanks @publicarray, for bringing this up!

**Comment by pyllyukko** [comment]
> The con is what you've said, it's maybe not that easy to scroll trough the comments. I'm unsure, if it's better to submit each stuff at it's own then we can close it.

Each stuff at it's own, thank you :) There is so much discussion going on in all these issues (thank you all for that!), that it's better to discuss each topic on it's own "thread" and try to keep on the subject.

**Comment by Roman-Nopantski** [comment]
FYI:
// disable Web Audio API (FF51+)
   // https://bugzilla.mozilla.org/show_bug.cgi?id=1288359
user_pref("dom.webaudio.enabled", false);

**Comment by pyllyukko** [comment]
@Roman-Nopantski: Thanks!
