### ISSUE TITLE
SHA-1 removed 

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#152]
With Tor v6.0 Final alias ESR >45 SHa-1 support [was dropped](https://blog.mozilla.org/security/2016/01/06/man-in-the-middle-interfering-with-increased-security/). 

Maybe someone could test <code>security.pki.sha1_enforcement_level</code>, see also [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1236975) & [here](https://bugzilla.mozilla.org/show_bug.cgi?id=942515).

**Comment by pyllyukko** [comment]
Related issue: #114

**Comment by CHEF-KOCH** [comment]
Was now removed with latest FF. I close here.

**Comment by Roman-Nopantski** [comment]
FYI: Rather than create a new issue, I'll just stick a comment in here. FF hasn't dropped SHA-1 support (but they want to). In fact, in FF48 they have created a new variable, as the new default.

currently (line 603), you have

>
// Kill SHA1 certificates
// https://bugzilla.mozilla.org/show_bug.cgi?id=942515#c32
user_pref("security.pki.sha1_enforcement_level", 2);

set at 2 isn't killing them, but anyway, there is now an option to set as 3. here is some cleaner info for the js ( you can see the 4 test examples here: https://dxr.mozilla.org/mozilla-release/source/security/manager/ssl/tests/unit/test_cert_sha1.js#74 )

> 
// disable or limit SHA-1
   // 0 = allow SHA-1, 1 = forbid SHA-1, 2 = allow SHA-1 only if before 2016
   // 3 = allow SHA-1 for certificates issued before 2016 OR by an imported root.
user_pref("security.pki.sha1_enforcement_level", 1);

FF48 default is 3. Personally I have been running at 2 for several months with no problems (I have no 3rd party AV MiTM), and am now disabling it entirely (time will tell if it breaks too much of the internet for me)

**Comment by pyllyukko** [comment]
> FF48 default is 3. Personally I have been running at 2 for several months with no problems (I have no 3rd party AV MiTM), and am now disabling it entirely (time will tell if it breaks too much of the internet for me)

Let us know how that works out. When I tried it a while back, the world clearly wasn't ready ([see here](https://github.com/pyllyukko/user.js/pull/114#issuecomment-189153927)).

**Comment by Roman-Nopantski** [comment]
> Let us know how that works out. When I tried it a while back, the world clearly wasn't ready

Will do. Read your linked comment - same as you, around Jan/Feb I did the same, found a bit too much broke. Hence trying it again 6 months later.

Anyway, only posted the comment to let you know the new variable and if you wanted to put the variable info into the user.js :)

**Comment by berrythesoftwarecodeprogrammar** [comment]
I've been using `1` for a long time now and the only site which ever has issues is `twitter.com`, css and images fail to load, because of the twimg.com subdomains I think. I change it to `2` when I want to use Twitter.

**Comment by Roman-Nopantski** [comment]
That's strange - I just cleared my memory cache, checked I was using `1` , logged into twitter and everything looks normal - all the https://abs.twimg.com css and js and images are in my cache - they only NS_BINDING_ABORTED I had was on a POST, nothing on GET. Might be a different issue, but pagination is broken (I never use twitter anyway, only have an account for testing since its such a popular thing).
