### ISSUE TITLE
Re-enable dhe_rsa_(camellia|aes)_256_sha ciphers at some point

### ISSUE THREAD

**Issue by pyllyukko** [pyllyukko/user.js#19]
These two cipher suites were disabled in #18 due to the [LogJam](https://weakdh.org/) vulnerability. As they still have the [forward secrecy](https://en.wikipedia.org/wiki/Forward_secrecy) property, it might be good idea to re-enable them at some point in the future.

Related:
* [RFC 5932](https://tools.ietf.org/html/rfc5932) (Camellia Cipher Suites for TLS)

**Comment by CHEF-KOCH** [comment]
[Calomel](https.//calomel.org) addon use the following options:
* 256 bit Perfect Forward Secrecy and GCM ciphers [x]
* 128 bit Perfect Forward Secrecy and stronger
* 128 bit and stronger 
* all ciphers allowed 

These toggles are quite useful (imho). Mozilla itself wrote to me that some of them are getting removed in the future (and so in Calomel). Besides that you can use the maximum strongest settings and only allow the sites you trust via _security.tls.insecure_fallback_hosts_ to make exclusions instead of generally allow/disallow them globally.

**Comment by pyllyukko** [comment]
Maybe these cipher suites should be forgotten in favor of TLSv1.[23], which seem to use only cipher suites with SHA-2 signature algorithms.
