### ISSUE TITLE
ghacks user.js 

### ISSUE THREAD

**Issue by publicarray** [pyllyukko/user.js#205]
I just wanted to link to a similar project that might be of interest people here. Maybe we could link back to them? Anyway I'm giving ghacks user.js a go in a new FF profile.
 
v0.11 article: http://www.ghacks.net/2017/02/12/ghacks-net-firefox-user-js-config-0-11-is-out/
v0.11 direct link: http://www.ghacks.net/files/user.js%20[ghacks]-0.11-dark.html
v0.11 download link: http://www.ghacks.net/download/130328/
Latest version is always at: http://www.ghacks.net/2015/08/18/a-comprehensive-list-of-firefox-privacy-and-security-settings

P.S. http://www.uniquemachine.org is an interesting website. It tries to get a fingerprint on the machine not just the browser.

**Comment by nodiscc** [comment]
@publicarray You could submit a patch to add uniquemachine.org to https://github.com/pyllyukko/user.js#online-tests

I think @Roman-Nopantski is the maintainer of the ghacks.net user.js file and his work is closely related/based on this project. I just wish we would standardize on a common base file, so that our respective changes would be easier to diff (eg. see my own changes at https://github.com/pyllyukko/user.js/compare/master...nodiscc:dbu#files_bucket, I regularly merge @pyllyukko's user.js on top of my changes. Bot files can easily be compared, unlike the ghacks file which has 1. no common git history 2. is heavily commented/modified)

**Comment by pyllyukko** [comment]
Yes, we are aware of the gHacks user.js and the author (@Roman-Nopantski) regularly contributes to this project also (thanks, Pants!).

@nodiscc: You are absolutely right! We should come up with a seamless way to compare between each projects.

@Roman-Nopantski: Is there a reason why your project is not using Git? :)

**Comment by Roman-Nopantski** [comment]
Sorry guys (and gals)... I didn't mention the new release, as I didn't want to come across as all spammy. The changelog, if it helps, lists everything I added in the last 7 months.

Diff compare .. they're too divergent, to be honest. The user.js currently has 219 "user_prefs(" in it. The ghacks one has 564. I also think the purposes and some methods are slightly different (one example of many: I use an inactive deprecated section, you keep deprecated prefs alive for compatibility). These differences doesn't mean that they can't help enhance each other, of course.

As for github... (sorry for the short story coming up) .. the initial list was mentioned in a ghacks thread and after the ghacks community asked, Martin published it, where, with the readers driving me, it was cleaned up and added to. I'm not an expert in these things - although having said that, it's been two+ years of part-time reading-researching-tweaking-testing etc. But I am still NOT knowledgeable, and nowhere near understanding half the web technologies.

Its now at the point where it has 464 stable+ (FF51+) prefs listed, 416 active, out of a total of 3000 possible. It's like mapping the human genome! It's been cleaned up to the nth degree, and is no longer my work, TBH. People like earthling, have driven a lot of change (doing diffs between releases to determine all changes to prefs - added/changed/removed - and we investigate them all). We've started building in version numbering for when prefs first appear, and when they deprecate, added hidden pref tags, and so on. I also think the numbering system and warnings/troubleshooting are pretty unique/cool.

Out of respect for Martin and the ghacks community, I have kept it at ghacks. Each release is going to be my last, but then I end up doing another one, because .. ghacks readers and their support. I have toyed with the idea of githubbing it for 6 months. I asked Martin if I could use the ghacks name on it here, and he said he would be honored (and that he could still do occasional articles). Many others have said its time to git it.

But here's the kicker, I'm a github baby. So someone hold my ignorant hands and explain - I have to install a client, right? I don't want to install a client. I also do not understand a lot of the terms or what they do. I stopped coding after a lifetime (of some coding and other things), about 10 years ago. So I feel I am not the right person to do this, because I am a newbie :) . I'll just f**k it up. Although I am sure the learning curve is short. That, I feel like its a lot of work (responsibility) that I could do without.

That said, if anyone else here wants to github it, I will be on board - as long as it retains the ghacks name for Martin Brinkmann. earthling who is a massive contributor, has said he will also be on board with a gitted release. My one question in this regard is do I have to have a client installed to make changes, or can the owner set user permissions? (told you I was a git newbie).

So I have two options: git it myself if you can all help me and assure me its not hard and I won't screw up, or someone else does it, and I'll help (would love to be able to make changes if a non-owner can do that). I guess I should read a github 101 for dummies or something.

Sorry for the long post

**Comment by Roman-Nopantski** [comment]
@publicarray You seem to know what you're doing :) and will be aware that "out of the box" some things are turned off such as tracking protection, blocklists etc (so get uBlock Origin installed for some lists). It's why the troubleshooting section and warnings exist - everything not a warning should be good to go with zero to little breakage.

**Comment by publicarray** [comment]
@nodiscc
> submit a patch to add uniquemachine.org

done 👍 

@pyllyukko thanks, I was not aware, all good

@Roman-Nopantski first pants and all contributors many thanks! I really like the extensive comments in the file.
 
With regards to git it is possible to edit files without a desktop client. github.com could be your client of sorts. You won't have access to some of the advanced features but simple editing is possible using this website. 
For example open https://github.com/pyllyukko/user.js/blob/master/user.js and click on the pencel: 
![screen shot 2017-02-16 at 10 34 31 pm](https://cloud.githubusercontent.com/assets/5497998/23021607/813d6db8-f498-11e6-89a9-09b0886bfbd7.png). This will create a fork (copy of all files to your github account) that you can change and when you are done you can create a pull-request (send the changes back to pyllyukko/user.js)

Github does have a permissions system and can be setup such that multiple people can edit files directly without pull requests. l should say I'm by no means a git or github expert. Also a small note that git and github are different. git is a (command line) tool and github.com is a website that hosts repositories (code) using git. 

For the termenology github has a glossary: https://help.github.com/articles/github-glossary/
To start your own repository: https://help.github.com/articles/create-a-repo/

> some things are turned off

Thanks, Yes I'll definitely need to read through the file and make some changes 😄 

> get uBlock Origin installed

I have used uBlock Origin for a long time, It's my favorite extension by far.

**Comment by publicarray** [comment]
@Roman-Nopantski If yon't want to have the responsibility maybe setting up a github organisation is the best way for multiple people to help maintain the project?

**Comment by nodiscc** [comment]
* Basic git usage:  [1](https://rogerdudler.github.io/git-guide/) [2](https://try.github.io/levels/1/challenges/1) [3](http://www.wei-wang.com/ExplainGitWithD3/#) [4](https://git-scm.com/book/en/v2),  there are more ...
 * You can either use one of the available git clients (command-line `git`, graphical Github client...) or edit the file online as @publicarray suggested.
 * The repository can be hosted in multiple places (git is decentralized)
 * Retaining authors information is possible (eg. https://github.com/Kickball/awesome-selfhosted/blob/master/AUTHORS.md)

But @Roman-Nopantski I would start with
 1. Creating a github organization
 2. Creating a new repository for that org
 3. Clicking "New file"
 4. Pasting the contents of the current ghacks user.js in it
 5. Commiting the new file (with commit message `Import ghacks.net user.js 0.11 FINAL`)
 6. We can start working out the differences from there, pref by pref

Merging both works has great potential IMHO

**Comment by Roman-Nopantski** [comment]
https://github.com/ghacksuserjs/ghacks-user.js .. can't find "New file"

**Comment by Atavic** [comment]
@publicarray Uniquemachine.org focuses in particular on the GPU: https://github.com/Song-Li/cross_browser

**Comment by pyllyukko** [comment]
> So I have two options: git it myself if you can all help me and assure me its not hard and I won't screw up

Of course we will help you! Also, do you IRC? It's easier to communicate there regarding some details. More interactively that is. Join me at #user.js @ Freenode (see #167).

**Comment by pyllyukko** [comment]
I haven't used the WYSIWYG editor myself.

> https://help.github.com/articles/adding-a-file-to-a-repository/ is of no help.

Essentially, it's the stuff in the "…or create a new repository on the command line" section. With the exception of ```git add README.md``` where you would want to add every file of the gHacks user.js. I can do it also, but it would be better if you would.

**Comment by publicarray** [comment]
> add a new file

If you see this 
![screen shot 2017-02-17 at 8 43 55 am](https://cloud.githubusercontent.com/assets/5497998/23044788/6bd46dd2-f4ed-11e6-9264-0b8d33bac91d.png)

Click on the README link, you can change the file name or just use this link: https://github.com/ghacksuserjs/ghacks-user.js/new/master

**Comment by Roman-Nopantski** [comment]
Done. Its up .. one file... version: 0.12 BETA .. although I suppose version numbers and date are useless now :) Uploaded the file, pasting text loses all line breaks .. and I'm not manually adding 1751 line breaks.

All yours guys, I'll start a issue for who to add as team members and admin and stuff - thanks so much for your help (I must come across as a moron, which is just as well, because I probably am).

**Comment by pyllyukko** [comment]
> version numbers and date are useless now

Not necessarily. You can still use those via ```tag```s and they will appear in [releases](https://github.com/ghacksuserjs/ghacks-user.js/releases). Since you have used a versioning scheme before with gHacks user.js, it would make sense to continue.

> thanks so much for your help (I must come across as a moron, which is just as well, because I probably am).

You're welcome :) And no, you're not a moron. Git can be confusing in the beginning.

**Comment by Roman-Nopantski** [comment]
FYI: Martin just told me that the ghacks user.js was downloaded 1596 times in the first 5 days - which blows my mind.

> Merging both works has great potential IMHO, thank you for maintaining them.
Absolutely. Both versions can offer each other lots. This repository has a lot of info on portable, linux and especially CA's etc - the ghacks one on the other hand is just a txt file. Anyway - pillage away .. arrrh :)

**Comment by nodiscc** [comment]
I have started comparing this repo's and the ghacks one `user.js` files:

```
git clone https://github.com/ghacksuserjs/ghacks-user.js/ ghacks-user.js
git clone https://github.com/pyllyukko/user.js pyllyukko-user.js
egrep "^user_pref" ghacks-user.js/user.js | sort  > ghacks.txt
egrep "^user_pref" pyllyukko-user.js/user.js | sort | sed -e 's/[[:space:]]\+/ /g'  >| pyllyukko.txt
```

Now `diff` doesn't report the differences in a useful way (2 big blobs of text), but `meld` does:

![ghacks-diff](https://cloud.githubusercontent.com/assets/3950390/23093265/8fdb4628-f5de-11e6-9be4-458a20b03be5.png)

**Comment by publicarray** [comment]
while I was editing the ghacks-user.js I did a very quick of setting that differed from the file I had used before. The notable prefs that I found in pyllyukko/user.js but not in the ghacks-user.js are:

```js
// Disable dom.mozTCPSocket.enabled (raw TCP socket support)
// https://trac.torproject.org/projects/tor/ticket/18863
// https://www.mozilla.org/en-US/security/advisories/mfsa2015-97/
// https://developer.mozilla.org/docs/Mozilla/B2G_OS/API/TCPSocket
user_pref("dom.mozTCPSocket.enabled",               false);

// disable Gnome Shell Integration
user_pref("plugin.state.libgnome-shell-browser-plugin",     0);

// https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_Desktop#Firefox_37_onwards
user_pref("devtools.debugger.force-local",          true);

// https://wiki.mozilla.org/Privacy/Reviews/Necko#Principle:_Real_Choice
user_pref("network.seer.enabled",               false);

// Disallow NTLMv1
// https://bugzilla.mozilla.org/show_bug.cgi?id=828183
user_pref("network.negotiate-auth.allow-insecure-ntlm-v1",  false);
// it is still allowed through HTTPS. uncomment the following to disable it completely.
user_pref("network.negotiate-auth.allow-insecure-ntlm-v1-https",      false);

// CSP https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Introducing_Content_Security_Policy
// [already enabled by default in modern FF]
// user_pref("security.csp.enable",                true);

// https://bugzilla.mozilla.org/show_bug.cgi?id=855326 [personal preference]
user_pref("security.csp.experimentalEnabled",           true);

// http://kb.mozillazine.org/Browser.sessionstore.postdata
// NOTE: relates to CIS 2.5.7
user_pref("browser.sessionstore.postdata",          0);

// http://kb.mozillazine.org/Browser.sessionstore.enabled
// user_pref("browser.sessionstore.enabled",           false);

// CIS Mozilla Firefox 24 ESR v1.0.0 - 3.6 Enable IDN Show Punycode
// http://kb.mozillazine.org/Network.IDN_show_punycode
user_pref("network.IDN_show_punycode",              true);
```

not sure if it helps though.

**Comment by Roman-Nopantski** [comment]
> I don't know what's the best course of action yet.

I will create the list for you if you like. I will simply search mine for anything of yours and remove it, until I am left with I have that you don't - in a it's original structured, ordered list - gimme a few hours, I have other things to do. I will dump it in a pastebin

**Comment by Roman-Nopantski** [comment]
Almost done .. I got sidetracked sorry. **Are you sure you want it?**

 Including inactive prefs and excluding the ciphers: there are no legacy ones in ghacks, except those deprecated since I started the js almost 2 years ago - and this js has ciphers covered
- what pyllyukko has that ghacks doesn't - 21 prefs
- what ghacks has that pyllyukko doesn't - 360 prefs (74 inactive) (but I'm still finishing off the last tiny bit)

Obviously a lot of ghacks ones are overkill/future-proofing/ass-covering, or there for info, or added to make a section complete and comprehensive. That said, I can see a lot that make sense for yout o include. At the very least, it should give you something to mull over for a while, and keep you busy :) I will stick it up as a pastebin - it's still contains the relevant descriptions and links etc for those prefs remaining. It includes the deprecated section, because one of your goals is to be backward compatible.

**Comment by Roman-Nopantski** [comment]
http://pastebin.com/SLgdnPHJ .. Obviously there is some stuff in there that is not fit for your purpose - it's **everything* listed you haven't got. Paste self-destructs in 6 days, so grab a copy and start making issues!!! :) Hopefully anything that excites you, the references will help.

**Comment by pyllyukko** [comment]
@Roman-Nopantski: Thanks for the comparison. I made it available as a [gist](https://gist.github.com/pyllyukko/f5184fbb51b5e340f5637adee582c4d9).

> I don't know what's the best course of action yet.

Maybe I'll create one monster issue with all the prefs listed in the have_fun.js and we start it from there. Referencing existing issues when possible. Creating new issues for the "big topics", etc. One thing that I was thinking, that if I would create separate branch with the have_fun.js, we could comment individual lines of code and discuss 'em there?

**Comment by nodiscc** [comment]
#208 looks OK, I'll have a look at some of the prefs when I have time.

I think this issue can be closed.
