### ISSUE TITLE
'intl.accept_languages: en-US, en' breaks web application, causes Firefox bug

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#252]
I noticed this after trying pyllyukko's unmodified user.js which has `user_pref("intl.accept_languages",              "en-US, en");` (whereas precedently I didn't have this value in my own user.js). This caused a bug in a web application I use (Tiny Tiny RSS): https://tt-rss.org/forum/viewtopic.php?t=4027

I checked accepted languages manually through `Preferences > Content > Languages`: no accepted languages are listed (list is blank)

When trying to add a language manually (Select language form drop-down list > Add), no language is added (the list of accepted languages stays blank) and the browser console throws an error: `preference.value is null`. I believe this is a bug in Firefox.

Setting `user_pref("intl.accept_languages",              "en-us, en");` (no capital letters) solves both problems (my application breaking, and the languages prefs being blank/unchangeable + browser console error)

 * `intl.accept_languages` value should be `en-us, en`
 * Maybe the languages dialog bug should be reported to Mozilla (@fmarier is this right?)

**Comment by fmarier** [comment]
> Maybe the languages dialog bug should be reported to Mozilla (@fmarier is this right?)

It sounds like a minor bug (since you need to tweak your settings in `about:config` in order to get into a bad state), but it's probably also easy to fix (assuming it's just a matter of lowercasing the pref). So yes, it might be worth filing a bug.

**Comment by nodiscc** [comment]
Thanks, reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1349302

**Comment by pyllyukko** [comment]
I actually tried looking into this (which way it should be) when I added it in d80e67469d0219b46836f737441006512febcf0e, but then decided on ```en-US```.

**Comment by Thorin-Oakenpants** [comment]
This makes no sense to me. Changing the value to a rather unique value just because an add-on (and probably others) breaks. Default FF uses `en-US, en`. All this does is raise entropy IMO. Note: `browser.search.countryCode` and `browser.search.region` use `US`, and if you used `general.useragent.locale` it too would use capitals eg `en-US`

http://browserspy.dk/language.php 

Maybe the bug will address the issue with that add-on

**Comment by nodiscc** [comment]
@Thorin-Oakenpants please re-read the issue and double check some facts:

 * There is no mention of a broken addon.
 * Setting the pref to `en-US, en` causes the bug described at https://bugzilla.mozilla.org/show_bug.cgi?id=1349302 (*results in an empty Accept-Languages header*), which incidentally causes the web app bug I mentioned (this is how I discovered this bug; this patch is a fix for the Firefox bug, not my web application bug). Setting it to `en-us, en` makes everything work as expected.
 * "Default FF uses en-US, en" -> this is incorrect.
   * What http://browserspy.dk/language.php reports is not the actual value of `intl.accept_languages` - it reports the value of the _Accepted-Languages HTTP header_ - not the same thing, but one depends on the other.
   * `intl.accept_languages` depends on your installed browser locale, and OS configured locale.
   * The correct capitalization is `en-us, en` (as you can see by changing accepted languages manually from `Preferences > Content > Languages`).

**Comment by Thorin-Oakenpants** [comment]
I have no idea about your web app, I used the word broken, my bad. The point was that I thought (and still do) that you are changing this because of your web app. The bug filed with mozilla is fine, they will deal with it.

The browserspy link was simply to show that these values can be read - I thought that navigator.languages can be accessed (see http://browserspy.dk/showprop.php ) and indeed it can according to that link - not sure where it is getting that value from. Clearly not `intl.accept_languages` then. If that's the case then I guess it doesn't matter.

intl.accept_languages depends on your `installed browser locale` - well of course, that's obvious

"Default FF uses en-US, en" -> this is incorrect.
AFAIK, this is correct. I reset the value in mine and it defaults to capitals. Also see the DXR entries. Maybe we have entirely different builds - maybe its different in a linux build or something?

"The correct capitalization is en-us, en" - No. Just because that's what one component does, doesn't necessarily mean all the others uses of `US` are wrong. But clearly there is an issue of (in your bug) it being case sensitive or whatever.

https://dxr.mozilla.org/mozilla-central/search?q=intl.accept_languages&redirect=false
Everywhere you look it's capitalized. The naming convention suggests capitals eg fr-FR etc.

Not going to bother with this anymore. I raised the possibility that using lowercase was 1. used in FP'ing and 2. that it goes against mozilla's naming convention.

**Comment by nodiscc** [comment]
You are right. Having a space after the delimiter doesn't trigger any bug like the previous value, but for exactness sake we could remove the space.

**Comment by Thorin-Oakenpants** [comment]
It was just an observation, I didn't think the space would matter. I can't test your bug with tiny tiny rss, but I was having a play in the options. I can't trigger any error selecting items - my language list is full of items with lowercase. Did you strip out all languages or something? I don't quite follow.

Also, would be interesting to clear up the "default" when reset. I use portable FF and the default is with capitals. What are you using?

**Comment by nodiscc** [comment]
@Thorin-Oakenpants you can't reproduce the bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1349302 ?

 * Download/clone this user.js
 * Set `user_pref("intl.accept_languages", "en-US, en");`
 * Install the modified user.js to a new profile or install it system-wide
 * Go to `Preferences > Content > Languages`
  * 1st bug: the list of languages is blank
  * 2nd bug: you can't add new languages, clicking Add does nothing

Just tried creating a new profile **without user.js**, going to `about:config` and checking the default value of `intl.accept_languages`. It is `en-US, en`. Wtf.

**Comment by Thorin-Oakenpants** [comment]
1. My languages are not blank - they are set as expected (except they show as lowercase, even though the js says uppercase) - this is on Windows, using portable.
2. I can add languages no problems.

**Comment by Thorin-Oakenpants** [comment]
^^ edited
