### ISSUE TITLE
Consider Cookie Autodelete addon (WebExtension)

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#265]
When Webextensions lands, consider adding https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/ to the list of recommended addons.

**Comment by pyllyukko** [comment]
Well now webextensions have landed. Do you think this is relevant, considering all the other addons and persistent private browsing, which ditches all the cookies when closing the browser? I personally haven't felt the need to use a separate cookie remover addon.

**Comment by savyajha** [comment]
It allows one to whitelist sites and has container support, which is a pretty big deal. I like to keep my DDG settings, for example, which can only happen with cookie support. I have a persistent container for all Google stuff in which Google can set as many cookies as it wants, but Autodelete deletes all cookies outside that one container.

Might not really work for the regular version of this `user.js`, but I'd suggest it be a recommendation for the relaxed version.

**Comment by pyllyukko** [comment]
It also seems to be a "Featured Extension" in AMO. That's a good sign.

**Comment by CHEF-KOCH** [comment]
This issue should be closed, there is not much of a benefit in using "Cookie" cleaning extensions (overall spoken), especially for privacy oriented users because:
- You can already since year block/allow (white-/blacklist) cookies within the browser given settings (I agree it's not a fancy GUI but it works without addon).
- Most if not all Cookie cleaners can't clean Localstore among other places, this is due to internal changes and restrictions for addons and Browser.
- Using or recommended "cleaners" is always critical because they often cause more damage than they help, are "difficult" to configure and sometimes addons are just broken or not (fully) functional. if an addon crashes or [Mozilla screws up again](https://discourse.mozilla.org/t/fixed-certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047) and your addons aren't working your entire "defense" will _break_.

I think you or we should ensure we configure the browser so that it cleans them automatically without addons, and the user should get the control over a "global master toggle" to accept/reject cookies per-site basis.

**Comment by nodiscc** [comment]
I have been using this addon for a long time. I have disabled "permanent private browsing" mode and re-enabled caching/history/local storage in my user.js (the usability penalty was too high for me), so this addon provides a comfortable middle-ground. Even with the full hardened user.js I think it provides some benefits because it reduces cookie lifetime to the lifetime of the tab (as opposed to the lifetime of the browser session). The whitelist system is very easy to use, there are a lot of settings for fine tuning the addon.

PR at https://github.com/pyllyukko/user.js/pull/518
