### ISSUE TITLE
privacy.clearOnShutdown.passwords was removed in Firefox 42

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#290]
https://hg.mozilla.org/releases/mozilla-esr45/rev/fb4f42bbeb01

- [ ] move it to ignore.list

**Comment by Thorin-Oakenpants** [comment]
from the current master js (I am not sure if anything is hanging around in PRs)

- `browser.sessionstore.enabled` no longer exists (removed some time over 2 years ago, probably same time as the postdata pref below)
- `browser.sessionstore.postdata` no longer exists (99% sure this was removed in FF29)
- `plugins.hide_infobar_for_outdated_plugin` no longer exists (removed around FF33)
- `plugins.update.notifyUser` no longer exists (99% sure this was removed in FF50)
- `network.negotiate-auth.allow-insecure-ntlm-v1` + `network.negotiate-auth.allow-insecure-ntlm-v1-https` - removed around FF37
- `plugin.state.libgnome-shell-browser-plugin` no longer exists in DXR but I have no idea if is used in special linux builds or whatever - seems dead to me
- `browser.formfill.expire_days` is legacy and has no effect
- `browser.download.manager.retention` is legacy and has no effect

Also `browser.urlbar.maxRichResults` no longer controls the dropdown in this fashion. AFAIK (and it was tested by numerous people) it no longer acts as a "minimum" like it used to, just as a max now (from memory you can't make the dropdown less than 10 items, i.e if there are more than 10 items to list, you can't get it under showing at least 10)
```js
// "Setting the preference to 0 effectively disables the Location Bar dropdown entirely."
user_pref("browser.urlbar.maxRichResults", 0);
```

Should I keep letting you know things like this?

**Comment by pyllyukko** [comment]
> Should I keep letting you know things like this?

Your input is always much appreciated!

Still want to [point out](https://github.com/pyllyukko/user.js/blob/master/CONTRIBUTING.md#removing-settings), that we want the "hard facts" of the removal of any settings before removing it from the user.js.

**Comment by Thorin-Oakenpants** [comment]
I fully understand what "hidden" prefs are (from the contributing#removed-settings) and I do appreciate it is nice to have an actual source. That said, I always check DXR (and before that MXR). I use the mozilla-central branch FYI. And I always test. I am thorough. I don't believe everything I read, I always investigate. But I am not going back 2 or 3 years or more to find old bugzillas if they exist - some in the past have been impossible to find.

FYI: here is one https://bugzilla.mozilla.org/show_bug.cgi?id=449596 `browser.sessionstore.enabled` was removed 9 years ago in FF 3.1a2

Considering my record (here and with the ghacks js), I would have expected more (my word has been taken at face value before to make changes). It's almost at the point where I can't be bothered, because I feel that whatever I say is ignored - I have mentioned `browser.urlbar.maxRichResults` before, for example - we tested this in the ghacks repo, myself, earthlng, and others.

Hence why I didn't say anything about double windows on launch with `privacy.clearOnShutdown.openWindows` until other people brought it up, and even then, I had to fight and scream. And now others have brought it up again, and yet it still hasn't been changed. Maybe I don't explain things well enough. I just don't get why you would enable it and subject EVERYONE to double windows on launch (I assume this happens on Linux, but on Windows for sure).

Hence why I didn't mention in-line svg blocking youtube. Because I just get shot down. Consider this: the monster diff: The SVG was a WONTFIX (I had in-line svg blocked in that diff). But as soon as someone else suggests it, it's yeah, commit. It's like I'm not taken seriously. That's not the only one.

All the tests for browser.formfill.expire_days and browser.download.manager.retention were done in one of the ghacks issues. plugins.update.notifyUser is recent (maybe I could have looked that one up) but the rest are old as hell (17 to 20 releases ago).

I do plan on actually adding in bugzilla info into the deprecated list in the ghacks js. eg where `# 1322736` is used to denote https://bugzilla.mozilla.org/show_bug.cgi?id=1322736

```js
/* 2507: (53+ #1322736) disable keyboard fingerprinting ***/
   // user_pref("dom.beforeAfterKeyboardEvent.enabled", false);
```

/end of temper tantrum

**Comment by pyllyukko** [comment]
> I fully understand what "hidden" prefs are (from the contributing#removed-settings) and I do appreciate it is nice to have an actual source. That said, I always check DXR (and before that MXR). I use the mozilla-central branch FYI. And I always test. I am thorough. I don't believe everything I read, I always investigate. But I am not going back 2 or 3 years or more to find old bugzillas if they exist - some in the past have been impossible to find.

For this project, it's not "nice to have", it's mandatory. I know that you're thorough, it's not about that and you shouldn't interpret it as distrust against your word.

> FYI: here is one https://bugzilla.mozilla.org/show_bug.cgi?id=449596 browser.sessionstore.enabled was removed 9 years ago in FF 3.1a2

Thanks!

**Comment by nodiscc** [comment]
> going back 2 or 3 years or more to find old bugzillas if they exist

@Thorin-Oakenpants yeah this is a chore, searching on https://hg.mozilla.org/mozilla-central/ is can help a lot when looking for a particular _change_ (an equivalent would be `hg clone https://hg.mozilla.org/mozilla-central/` and searching the log with `hg log`...). Whereas DXR only shows the codebase at a set point (tip/release/esr52/esr45/esr31...), you have to manually switch branches/use `Blame` to find changes...

For example searching for https://hg.mozilla.org/mozilla-central/log?rev=browser.sessionstore.enabled shows that it was removed in https://hg.mozilla.org/mozilla-central/rev/e712e96d7861 (there's also a link to bug 449596 in that commit message). Easier than digging bugzilla or DXR. (Though the pref name *must* be in the commit message).

hg.mozilla.org has a log dating back to Firefox 3.5 ([release branch mozilla-1.9.1](https://hg.mozilla.org/releases), July 2011).

> browser.urlbar.maxRichResults

@pyllyukko removed it in https://github.com/pyllyukko/user.js/commit/116d9863de4b4b946d699368bebd7e7dff0b7903 but wrongly, I believe, it _does_ have the effect I describe (doesn't it?), please see the commit comment.

> browser.download.manager.retention

Still present in [ESR45](https://dxr.mozilla.org/mozilla-esr45/source/toolkit/components/downloads/nsDownloadManager.cpp#79), [52](https://dxr.mozilla.org/mozilla-esr52/source/toolkit/components/downloads/nsDownloadManager.cpp#80), and [in the current release (53)](https://dxr.mozilla.org/mozilla-release/source/toolkit/components/downloads/nsDownloadManager.cpp#), not there anymore in the latest firefox-central revision (unreleased). What is wrong about it?

I agree with @pyllyukko that facts based on actual code changes are v

**Comment by Thorin-Oakenpants** [comment]
Its not about the "chore", I always provide links and references with current issues. It's more of a "do I really need to provide (and find) source for items that are CLEARLY no longer there" - like removed 8 YEARS AGO (bit of an outlier admittedly) or those others gone for well over 2 years.

That said, because I am so diligent (and anal), I will find every instance of deprecation source in my own deprecated list (so you can use it as a source as well - its the tail end of the ghacks js), and any item I think is legacy (or broken) I will create a new topic, outlay a test step by step, and provide proof (for windows) and ask for replication on Mac and Linux. You guys are both watching the ghacks repo, but said nothing when all these were brought up. I watch and (almost) always comment here. I feel abused and used now, sorry. Nodiscc, I will include you as an @nodiscc when I need a linux test :)

**Comment by Thorin-Oakenpants** [comment]
^^ the svg pref causing youtube controls to not display, and the privacy.clearOnShutdown.openWindows causes two windows to load on next FF launch

**Comment by Thorin-Oakenpants** [comment]
I do not want to create a new issue - so I'll just mention this here.

```js
// PREF: When browser.fixup.alternate.enabled is enabled, do not fix URLs containing 'user:password' data
user_pref("browser.fixup.hide_user_pass", true);
```

I believe the description is incorrect. The URL is *still* fixed, but it also strips the `user:password`

`http://user:password@foo` -> `http://user@(prefix)foo(suffix)` and not `http://user:password@(prefix)foo(suffix)`
