### ISSUE TITLE
SEC_ERROR_OCSP_SERVER_ERROR when using HTTPS Everywhere Block all unencrypted requests on certain sites

### ISSUE THREAD

**Issue by matthewburnett** [pyllyukko/user.js#321]
Firefox 54, 64 bit, Windows 10, unchanged user.js, system wide install.

After enabling Block all unecrypted requests, certain sites fail to load with the error SEC_ERROR_OCSP_SERVER_ERROR. I've identified google.com and github.com to fail to load, other https sites seem to load just fine. Turning off Block all unencrypted requests and restarting firefox fixes the issue.

**Comment by pyllyukko** [comment]
You mean via HTTPS Everywhere?

**Comment by nodiscc** [comment]
A workaround is to set `security.OCSP.require` to `false`.

**Comment by Atavic** [comment]
Another possible cause: https://github.com/pyllyukko/user.js/issues/246#issuecomment-294820297

**Comment by pyllyukko** [comment]
OCSP servers tend to have some random problems every now and then. As @nodiscc said, if you have ```security.OCSP.require``` as true (which is set by our user.js), Firefox doesn't let you to the site as it can't check the revocation status of the cert.

Usually the OCSP servers start working again after a while. @cynotek's case sounds like a temporary problem with the OCSP servers.

@cynotek: Can you tell whether the problem persisted or was it only temporary?

At least I couldn't reproduce the problem.

**Comment by bitpixl** [comment]
This week I've been having these issues as well, mostly on google.com sites and startpage.com. It seems (from experience) that this is coming from the OCSP servers, because last time I had this, things started working later on without changing anything. For now I've set `security.OCSP.require` to false.

I'm also using https everywhere but I doubt that's part of the problem.
