### ISSUE TITLE
Stop clearing cookie exceptions?

### ISSUE THREAD

**Issue by firefoxguy** [pyllyukko/user.js#326]
How can I stop user.js from clearing my cookie exceptions on exit? I want to block cookies by default but set exceptions to websites such as email, github etc.

**Comment by savyajha** [comment]
First off, wow, please do not post your entire `user.js` here. At least, not without code blocks. And since your `user.js` is very similar to upstream, maybe it's a good idea to merely tell us what changes you've made?

Second, please check your problem on a fresh firefox profile. You can go to `about:profiles`, create a new profile, add your `user.js` there and check whether you're facing the same problems.

Finally, if you see that the problem persists, maybe you can check your settings one by one and figure out what is causing this problem? The only cookie-related setting of mine which is different from yours is that I've got `user_pref("network.cookie.cookieBehavior", 1)` instead of what you've got, and my exceptions work fine.

**Comment by firefoxguy** [comment]
Sorry. After doing a bit of testing with a different profile it turns out CCleaner was clearing my exceptions I fixed this by unchecking "Site Preferences"

**Comment by pyllyukko** [comment]
So you got it resolved? Should be a matter of ```browser.privatebrowsing.autostart```, ```privacy.clearOnShutdown.cookies``` & ```network.cookie.lifetimePolicy```. You can also test the [relaxed](https://github.com/pyllyukko/user.js/tree/relaxed) branch.

**Comment by Atavic** [comment]
It was Crap Cleaner.exe
