### ISSUE TITLE
Consider removing old settings

### ISSUE THREAD

**Issue by Genbox** [pyllyukko/user.js#33]
To simplify the config, consider removing old settings that no longer apply. As of Firefox 39.0.3, the following settings no longer apply:

- [x] browser.frames.enabled
- [ ] browser.download.manager.retention
- [ ] browser.history_expire_days
- [ ] browser.history_expire_sites
- [ ] browser.history_expire_visits
- [ ] general.useragent.override
- [ ] plugins.hide_infobar_for_outdated_plugin

**Comment by Hunter-Github** [comment]
Would disagree with that: there are also ESR browsers out there. Historically significant options may be simply put in a single section of the file.

**Comment by Genbox** [comment]
This issue is just a consideration, not an actual issue which needs to be fixed right away. I think it would be prudent to keep track of deprecated settings along the way, and remove them as new releases of Firefox ESR comes out.

That being said, The the settings are also not present in the current version of Firefox ESR.

**Comment by Genbox** [comment]
The following settings are also not present in current Firefox and Firefox ESR releases.

browser.sessionstore.enabled
browser.sessionstore.postdata
javascript.options.methodjit.chrome
javascript.options.methodjit.content
media.gmp-gmpopenh264.enabled
network.dns.disablePrefetchFromHTTPS
spdy.enabled.v3
network.negotiate-auth.allow-insecure-ntlm-v1
network.negotiate-auth.allow-insecure-ntlm-v1-https
security.enable_ssl3
security.enable_tls_session_tickets
security.ssl3.dhe_rsa_camellia_128_sha
security.ssl3.dhe_rsa_camellia_256_sha
security.ssl3.dhe_dss_camellia_128_sha
security.ssl3.dhe_dss_camellia_256_sha
security.ssl3.rsa_camellia_128_sha
security.ssl3.rsa_camellia_256_sha
security.ssl3.rsa_null_md5
security.ssl3.rsa_null_sha
security.ssl3.ecdh_rsa_null_sha
security.ssl3.ecdhe_ecdsa_null_sha
security.ssl3.ecdhe_rsa_null_sha
security.ssl3.ecdh_ecdsa_null_sha
security.ssl3.dhe_dss_aes_128_sha
security.ssl3.dhe_dss_aes_256_sha
security.ssl3.dhe_dss_des_ede3_sha
security.ssl3.dhe_rsa_des_ede3_sha
security.ssl3.ecdh_ecdsa_aes_128_sha
security.ssl3.ecdh_ecdsa_aes_256_sha
security.ssl3.ecdh_ecdsa_des_ede3_sha
security.ssl3.ecdh_ecdsa_rc4_128_sha
security.ssl3.ecdh_rsa_aes_128_sha
security.ssl3.ecdh_rsa_aes_256_sha
security.ssl3.ecdh_rsa_des_ede3_sha
security.ssl3.ecdh_rsa_rc4_128_sha
security.ssl3.ecdhe_ecdsa_des_ede3_sha
security.ssl3.ecdhe_rsa_des_ede3_sha
security.ssl3.rsa_1024_rc4_56_sha
security.ssl3.rsa_fips_des_ede3_sha
security.ssl3.rsa_rc2_40_md5
security.ssl3.rsa_rc4_40_md5
security.ssl3.rsa_seed_sha

**Comment by CHEF-KOCH** [comment]
Maybe an separate ESR user.js would be the answer to not break stuff.

**Comment by CHEF-KOCH** [comment]
I'm not sure about <code>general.useragent.override</code> but it seems somehow still working under 39.0.3/40, as explained over [here](https://github.com/dillbyrne/random-agent-spoofer/issues/275), it may just need to add manually in about:config. Afer some browser restarts and tests I can say that after adding it back, it still works with <code> browserspy.dk/browser</code> from RAS.

The other mentioned options are deprecated, since Mozilla removed SSL3. All other things are now handled internal (reverting them back via about:config) doesn't seems to work.

**Comment by pyllyukko** [comment]
We can certainly clean up the ```user.js``` along the way, but I want to be 100% sure that the settings are really gone. That would mean a reference to Mozilla's bug tracker that clearly states that this and that setting has been removed or otherwise obsoleted. Not having some setting in ```about:config``` is not necessarily enough.

> Maybe an separate ESR user.js would be the answer to not break stuff, on Tor's ESR version there is no necessary to use a hardened config since it's already set to max and the rest can be controlled via the torbutton.

I'm not too keen on having separate versions of this, especially when this would only be a cosmetic change.

**Comment by CHEF-KOCH** [comment]
Well, since user.js is a product that claims to harden the FF settings and small other things I think we can remove the settings to the one simple reason, if you not update your browser (you will see a notice/popup by default) you simply not care about security. It's widely known that updates/upgrades is a very important aspect of security. And because of this I think we should stay on the line. As I already said, entirely removing isn't useful in some cases - but we could make a history.txt, a separate file or simply use the existent one and store the entries in a _deprecated_ category within user.js. So the benefit would be that everyone could directly see what is outdated + maybe something like a timeline (history). Of course in case someone like to use an older FF or ESR version (because crashes in the current release or other problems) he/she could uncomment the lines which he really needs. 

The only problem I see is a risk, using old entries that are removed from about:config (not visible) could be still present as a fallback for _special_ users. E.g. there are still about:config _speed_ tweaks from 3 years that still working for FF40 but they're not visible (user needs to add a new value for this).

**Comment by nodiscc** [comment]
> store the entries in a deprecated category within user.js

As a user of this project I would like this. Or just comment out the relevant lines, adding `deprecated as of Firefox $version` on line end. I would prefer this over searching in the git history why a particular setting is not there (has it been removed? deprecated? do we need to add it?)

**Comment by CHEF-KOCH** [comment]
The benefit of storing the entries within the same file would be that an addon could easier detect them by search for keys like 'deprecated' or 'outdated' and shows additional options. Speaking about the future. With an separate file for historical reason that would of course also be possible but needs more interaction since two files need to be maintained. To commit it under GitHub would have the benefit that it could also be parsed by the sha-1 under the addon + it would be always persistent no matter what will be changed on the file. 

Personally I see that very similar, old stuff needs to removed because nobody really needs it but as now said we must ensure that it doesn't have any effect anymore + we may need to respect ESR versions (which not that much often change xyz feature like normal releases).

Again I only see an good solution in an addon, which detect the used FF version, check existent entries + parse the .js file, that would never need much user input. But right now I'm far away from this since I not know how to remove old entries that was set by user (there is no api for it? - so you only can right click on it and pres 'reset' .. that's annoying, especially the time you need to reveal what is not used anymore .... uargh!!).

**Comment by nodiscc** [comment]
I think the preferred approach is to append affected Firefox version numbers to the pref description, like we did for the Battery API prefs (https://github.com/pyllyukko/user.js/blob/master/user.js#L72).

This needs to be made clearer in the README, and then this issue can be closed.
