### ISSUE TITLE
Look into policies.json & GPO deployment

### ISSUE THREAD

**Issue by pyllyukko** [pyllyukko/user.js#389]
* <https://support.mozilla.org/en-US/products/firefox-enterprise/policies-enterprise>
* <https://github.com/mozilla/policy-templates>
* #388

**Comment by Atavic** [comment]
The DISA STIG by DOD and Stigviewer, linked [here](https://github.com/mozilla/policy-templates/issues/234#issuecomment-419960343) are worth a look.

**Comment by nodiscc** [comment]
https://addons.mozilla.org/en-US/firefox/addon/enterprise-policy-generator/

**Comment by intika** [comment]
The new enterprise policy are very limited, and the settings that could be applied to about:config are very limited... 

as an alternative i personally use the classic deployment system. [Firefox_Enterprise_Deployment](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Enterprise_deployment_before_60) it still work (Tested in v63) i guess because the new system is not yet fully operational and/or we can not yet edit all the settings 

user.js just change the settings; To avoid firefox and/or other source to change those settings it preferable to lock them with the method linked above, it is still the method to go for company that want to lock some settings, the new one is still under dev. and need to be unlocked to all the settings, its not yet the case... or may be firefox is going on a creepy road and willing to disable access to all the settings...

**Comment by nodiscc** [comment]
I was attempting to change the default search engine through user.js, and found that it could not longer be modified in this way. Instead, it seems that `policies.json` must be used. [[1]](https://superuser.com/questions/1372679/how-to-set-duckduckgo-as-default-search-engine-using-user-js) [[2]](https://bugzilla.mozilla.org/show_bug.cgi?id=1029148)

There is a very basic implementation  of `policies.json`-based settings already in this repository: https://github.com/pyllyukko/user.js/blob/3779a7cd13a913dcd913d5ad4f67cc4ee4c66d0e/Makefile#L19


```make
.PHONY: policies.json # generate policy file (https://github.com/mozilla/policy-templates/blob/master/README.md)
policies.json:
	jq -n -M "{\"policies\": {\"OfferToSaveLogins\": false, \"DisableBuiltinPDFViewer\": true, \"DisablePocket\": true, \"DisableFormHistory\": true, \"SanitizeOnShutdown\": true, \"SearchBar\": \"separate\", \"DisableTelemetry\": true, \"Cookies\": {\"AcceptThirdParty\": \"never\", \"ExpireAtSessionEnd\": true}, \"EnableTrackingProtection\": {\"Value\": true}, \"PopupBlocking\": {\"Default\": true}, \"FlashPlugin\": {\"Default\": false}, \"DisableFirefoxStudies\": true}}" >| policies.json
```

I will look into what settings can be changed using the policy mechanism, if they are relevant to this user.js, and submit a patch to better document the deployment of this config file.

**Comment by nodiscc** [comment]
PR at https://github.com/pyllyukko/user.js/pull/546
