### ISSUE TITLE
Why disable web notifications

### ISSUE THREAD

**Issue by TerkiKerel** [pyllyukko/user.js#392]
Hi,

I wonder why we disable the web notifications? Is there any privacy concern if we dn't accept the web notification from any web site?

Thank you

**Comment by Atavic** [comment]
More like less bloat?

@pyllyukko both readme and user.js have a broken link:

https://support.mozilla.org/en-US/t5/Firefox/I-can-t-find-Firefox-menu-I-m-trying-to-opt-out-of-Web-Push-and/m-p/1317495#M1006501

While the working one should be:
https://support.mozilla.org/en-US/questions/1140439

**Comment by pyllyukko** [comment]
> More like less bloat?

Yep.

**Comment by Atavic** [comment]
In a general sense, this issue is somewhat similar to many others related to sites asking more and more from the visitors. I'm ok with web notifications, but only on trusted sites, like github when I'm logged in, all other web requests on random articles and casual pages are seen like bloated and not needed to me.

**Comment by pyllyukko** [comment]
As the question got answered, I'm closing this.
