### ISSUE TITLE
searchdefaulthash setting

### ISSUE THREAD

**Issue by Hunter-Github** [pyllyukko/user.js#43]
Tiphat to: https://security.stackexchange.com/questions/97376/

Source: https://hg.mozilla.org/mozilla-central/rev/462b94db3335

Also: https://dxr.mozilla.org/mozilla-central/search?q=searchdefaulthash&redirect=true&case=false&limit=84&offset=0

Looking for some way to find out what it is and how to turn it off if it infringes on user privacy.

**Comment by CHEF-KOCH** [comment]
That can't be fixed with any config and needs to be changed withing the source. Complicated stuff like font fingerprinting or just example isn't even fully protected in Tor's Browser Bundle, so I don't think we need to link to everything that is new and comes out of the blue. 

Metadata are a common problem and not only on search, it's on email, surfing, video/audio, whatever so that isn't easy to fix.

**Comment by pyllyukko** [comment]
Hmm. No idea what that might be.

**Comment by CHEF-KOCH** [comment]
?

**Comment by nodiscc** [comment]
Searching for `getVerificationHash(defaultEngine))` returns this page https://bugzilla.mozilla.org/show_bug.cgi?id=1029148. `getVerificationHash()` is related to preventing malicious modification of the default search engine (in this context)

**Comment by nodiscc** [comment]
My latest comment/link (from 2015...) is so far  the most relevant information source for this pref and nothing new has been brought up. I think this can be closed.
