### ISSUE TITLE
privacy.resistFingerprinting breaks shortcuts

### ISSUE THREAD

**Issue by elbaro** [pyllyukko/user.js#443]
With `privacy.resistFingerprinting=true`, site shortcuts and extension shortcuts do not work. (e.g. vimium-ff) Can you add a warning to comments?

https://bugzilla.mozilla.org/show_bug.cgi?id=1433592
https://bugzilla.mozilla.org/show_bug.cgi?id=1470828

**Comment by pyllyukko** [comment]
Thanks!

**Comment by Thorin-Oakenpants** [comment]
vimium-ff: that's not website breakage. That's extension breakage. Just saying. The fix here is that RFP will not apply to extensions: 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1450398
- https://bugzilla.mozilla.org/show_bug.cgi?id=1377744

https://bugzilla.mozilla.org/show_bug.cgi?id=1433592 is marked as **resolved fixed** back in FF59

I do see that https://bugzilla.mozilla.org/show_bug.cgi?id=1470828 is still open (opened 8 months ago, last commented 3 months ago - a lot has happened in 8 months), but AFAIK these keyboard issues are basically non-existent now - especially since they undid modifying the CTRL key, and they reverted to 4 OSes in JS navigator/UA. I'm not even sure the one in the ticket (Google Docs on MacOS even still applies)
