### ISSUE TITLE
Makes Firefox slow

### ISSUE THREAD

**Issue by e-t-l** [pyllyukko/user.js#458]
Has anyone noticed this making pages load slower? Have you identified a particular config responsible?

**Comment by Atavic** [comment]
No, maybe it's the missing disk cache?

**Comment by pyllyukko** [comment]
It is quite probable that this will make things slower. Also disabling the prefetches and stuff will affect your UX. Don't have any benchmarks on it though.

**Comment by brakenow** [comment]
I can live with that! Privacy matters more!

**Comment by CHEF-KOCH** [comment]
Some pages e.g. Google pages (YouTube, GDrive etc) using a new JavaScript implementation called "Polymer". This, according to some Mozilla Devs. causes a Firefox slow-down (up to 5x times) compared to Chrome/Chromium. 

The only way to fix this is to manually [optin into the old layout](https://twitter.com/cpeterso/status/1021626510296285185?lang=en). 

The disk cache argument is not the issue, it's Google, they just don't use W3C standards on their owns websites, because they have a 80+% market share.

**Comment by kikislater** [comment]
> Some pages e.g. Google pages (YouTube, GDrive etc) using a new JavaScript implementation called "Polymer". This, according to some Mozilla Devs. causes a Firefox slow-down (up to 5x times) compared to Chrome/Chromium.
> 
> The only way to fix this is to manually [optin into the old layout](https://twitter.com/cpeterso/status/1021626510296285185?lang=en).
> 
> The disk cache argument is not the issue, it's Google, they just don't use W3C standards on their own websites, because they have a 80+% market share with Chrome/Chromium, so why should they care?!

Still need to do that ?
