### ISSUE TITLE
This add-on requires a newer version of Firefox

### ISSUE THREAD

**Issue by antmak** [pyllyukko/user.js#463]
I have
```
This add-on requires a newer version of Firefox (at least version 65.0). You are using Firefox 60.0.
```
on sites like that https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/ when using 'relaxed' user.js. Although, I have firefox 66.0.5-1.fc29.x86_64

Could not found how to fix up it...

**Comment by Atavic** [comment]
You can get the xpi and load it locally, from the Version History on AMO,
or get the unsigned xpi from: https://piro.sakura.ne.jp/xul/_treestyletab.html.en

Issue mostly due to [privacy.resistFingerprinting](https://github.com/pyllyukko/user.js/blob/a2d2205901b9693aea4a3802ff02633a7486368c/user.js#L531) set as true.

// NOTICE: RFP breaks some keyboard shortcuts used in certain websites, see #443

Related: https://github.com/amoghbl1/tor-browser/issues/24

**Comment by antmak** [comment]
Really thank you for this. I took one from Version History. Thanks for the info
