### ISSUE TITLE
Finegerprint and cryptominer

### ISSUE THREAD

**Issue by g0rbe** [pyllyukko/user.js#467]
Hi!

What is the differences between `privacy.resistFingerprinting` and `privacy.trackingprotection.fingerprinting.enabled` ?

`privacy.trackingprotection.fingerprinting.enabled` is a relatively new setting in `about:preferences#privacy` alongside with the cryptominer setting (`privacy.trackingprotection.cryptomining.enabled`)

Are those worth nothing? Because i didn't found any related setting in your user.js.

Thanks,
    g0rbe

**Comment by Atavic** [comment]
*privacy.resistFingerprinting* is set as **true**. It comes from the tor browser project and it may cause some minor breakage: https://github.com/pyllyukko/user.js/search?q=privacy.resistFingerprinting&type=Issues

*privacy.trackingprotection.fingerprinting.enabled* and *privacy.trackingprotection.cryptomining.enabled* are subsets of the tracking protection, that's set as **true** [here](https://github.com/pyllyukko/user.js/blob/a2d2205901b9693aea4a3802ff02633a7486368c/user.js#L512).

While the single subsets can be enabled or disbaled from the GUI, the users that have *uBlock Origin* addon can ignore these, as uBo gives a much better choice for blacklists.

While using mozilla blacklists, one has to trust *Disconnect* - that even has whitelists included - instead of picking your own blacklists in uBlock Origin.

**Comment by g0rbe** [comment]
Now everything is clear.
Thanks for your helpful answer :)
