### ISSUE TITLE
CanvasBlocker addon paralyzed by user.js relaxed

### ISSUE THREAD

**Issue by lockntross** [pyllyukko/user.js#468]
I am here because I accidentally doubled up on canvas fingerprint detection... double negative it seems.
I added some changes to my prefs.js and it paralyzed CanvasBlocker addon  https://github.com/kkapsner/CanvasBlocker/issues/158 . Mozilla's resistFingerprinting does little to spoof anything, and is useless alongside CanvasBlocker.
user_pref("privacy.resistFingerprinting",	false);

So if anyone else is here because CanvasBlocker is crippled... here's your fix, change resistFingerprinting to false, or remove it. More information found on the issue above. 
THANKS!

**Comment by Thorin-Oakenpants** [comment]
I'll repost my answer in the above linked CanvasBlocker (CB) issue and continue it there, but want to quickly say here, for those that read this issue, that some items need addressing.

> Mozilla's resistFingerprinting does little to spoof anything, and is useless alongside CanvasBlocker.

^^ I cannot say this enough. This is absolutely terrible advice and not even a solution. Especially given that we don't know exactly **what** OP did, or **how** he did it, or any other details such as OS, Firefox version, CB version, and most importantly, what does "paralyzed" mean. That's not meant as a criticism of OP, it just needs clarifying, and may in fact be a genuine or potential bug.

* first of all, don't edit `prefs.js` (as a general rule: you can if you know what you're doing, but it is not recommended). You should be using `about:config` for real time changes (although some prefs require a restart), or for more permanent changes use a `user.js`
* OP states he paralyzed CB **because** he made changes to preferences. **By default** CB is not "paralyzed" (not sure what that means, the problem needs steps to reproduce (STR) and better analysis). This is a problem caused by OP (but may be a valid bug)
* Stating that the solution is to set *privacy.resistFingerprinting` to false is not a solution. The **real** solution is to find out exactly what OP did to cause CB for him/her to fail.
* RFP does **far more** (well over a hundred anti-fingerprinting measures) than just canvas protection, including some protections that cannot be solved outside of those provided by the Tor Uplift/RFP (e.g css media spoofing).

tl;dr: OP brought this issue on himself as CB & RFP work together out of the box (but what he did may be a valid/potential bug), and while disabling RFP clearly stops the conflict, it also causes far more harm than any good.
