### ISSUE TITLE
Strange issue Firefox switching to active window - Window ghost movements!

### ISSUE THREAD

**Issue by jkuj6** [pyllyukko/user.js#510]
Ive been having a very strange and annoying issue, it never used to happen before but only noticed it recently.

Basically, if you go to a site like Github, and as soon as you click sign-up, and while thats loading, you switch to another window, like Thunderbird, or your file browser, you will notice that as soon as Github finishes loading the captcha in the backgrounded window, it will switch to Firefox automatically as the active window.
Ive noticed only some sites do this, another of which is a banking site while logging-in half way, i noticed as i was switching between keepass and before i even double clicked the password, it switched me back to firefox active window.

This however, does not happen if you explicitly minimize the firefox window after refreshing the Github sign-up page.

I have successfully reproduced the issue on a VM and it does the same thing.  See the GIF video below.
![2021-03-22](https://user-images.githubusercontent.com/59932002/112042777-9518b100-8b50-11eb-9740-f7e93e557f00.gif)

To reproduce yourself:

1. Open 2 windows, one of them firefox and the other a file-browser or whatever.
2. Go to firefox and as soon as you click on the sign-up page, switch to your file-browser window and wait. (DONT minimize firefox, just switch windows)

I dont know about you, but this is over-board ridiculous and this never happened before. Can anyone say how websites are switching our active windows now and what option is causing this so it can be disabled?  Next thing you know is they will be controlling more than just our windows.

**Comment by jkuj6** [comment]
Anyone experiencing the same?

**Comment by nodiscc** [comment]
> Anyone experiencing the same?

No.

Cannot reproduce on Debian 10, firefox-esr `78.9.0esr-1~deb10u1`, latest `user.js` from master. I believe this is your window manager acting weird. It appears you are using Xubuntu, for what it's worth I'm also on XFCE, xfwm4 `4.12.5-1`. These are my windows focus settings

![image](https://user-images.githubusercontent.com/3950390/113510989-01ca7d00-954d-11eb-8970-9f675b801e2a.png)

- Can you try from a fresh [firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles?redirectslug=profile-manager-create-and-remove-firefox-profiles&redirectlocale=en-US) without user.js and check if the bug is still present?
- Can you try on another distribution (eg. using a live image from https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/) or desktop environment?
- Can you check your window manager settings?

**Comment by jkuj6** [comment]
Thanks for getting back to me.  I forgot to mention that i did test on a fresh Firefox profile with no user.js file.
I tested browser.tabs.loadDivertedInBackground changing it to true but thats not exactly what i wanted.

After various tests on various versions of Firefox on VM's, i realized that this issue only happens on Firefox v86.0.0.
After i upgraded to Firefox v87.0, that focus problem went away.  Seems it was a Firefox bug.

Thanks for the help!
