### ISSUE TITLE
Can Zenmate be edited?

### ISSUE THREAD

**Issue by cypherpunk** [pyllyukko/user.js#55]
Hello all

One question: can the Zenmate browser extension be edited?  The reason I'm asking is that when the web browser (Firefox or Chrome) is opened up with the internet lead disconnected, Zenmate still says that it is connected publicly to the last place the user chose, for example Germany.

This makes me think that the locations that can be chosen is in the code somewhere within the .XPI file, rather than coming from Zenmate's own server.  Is this right or not and if so, where is the code?  If it is right, how is it possible to add the UK to the list again?  

Many thanks.

**Comment by CHEF-KOCH** [comment]
> One question: can the Zenmate browser extension be edited?

It's against Mozilla's terms to hack/modify and re-publish hosted addons, since we have no permission from zenmate to do this. 
And it's doesn't matter on which location the server stands. Outside or inside the USA doesn't mean other agencies have not less interest on it. It's more the question which encryption the server uses, if he is compromised or something wrong to really show that he's insecure.

**Comment by nodiscc** [comment]
@cypherpunk How is this related to user.js?

**Comment by cypherpunk** [comment]
Hi CHEF-KOCH.  Thank you for clearing certain points up, no harm or offence intended to anyone, including the companies involved.  I was just curious if it could be done, that's all.

To nodiscc, not sure.  I clicked on new issue to start a new thread but it put me in that category.  Apologies if I've done it wrong and confused you!

**Comment by nodiscc** [comment]
@cypherpunk No harm done I was just confused because you seem to be on the wrong bug tracker. This is for [user.js](https://github.com/pyllyukko/user.js), a user.js configuration file for Mozilla Firefox designed to harden Firefox's settings. You should follow the link to zenmate support on https://addons.mozilla.org/en-us/firefox/addon/zenmate-security-privacy-vpn/

**Comment by pyllyukko** [comment]
Ok, so apparently this issue was addressed to the wrong project. @cypherpunk, please follow @nodiscc's instructions on how to report this to the Zenmate project.

I'm closing this issue. We can re-open it, if I misunderstood something.
