### ISSUE TITLE
Review and merge Icecat setting toggles?

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#58]
Hi, I was reading https://www.gnu.org/software/gnuzilla/ and found out it has a special `about:icecat` page

>  Adds a custom "about:icecat" homepage with links to information about the free software and privacy features in IceCat, and checkboxes to enable and disable the ones more prone to break websites.

Since people tend to recommend Icecat as a countermeasure to Firefox/Mozilla's recent "misbehaviour", and that Icecat is an outdated, low-workforce fork of Firefox which seems to only bring preinstalled addons and config changes, I think reasonable Free Software oriented distributions could simply distribute FF with an altered default config like this user.js. I have started working on a more "relaxed" preferences set in https://github.com/nodiscc/user.js/commits/dbu and I wish we could convice the Debian project to distribute this by default - there are several open bug requests on the Debian BTS for similar issues.

I am still curious whether Icecat has something more to offer; **would an Icecat user please copy-paste the settings found in `about:icecat` here?**

This would allow working on privacy/security/FOSS-oriented settings that user.js may be missing. The `about:icecat` is also similar to the request in https://github.com/pyllyukko/user.js/issues/25.

**Comment by berrythesoftwarecodeprogrammar** [comment]
ive suggested this before in another thread too. i really think that firefox customized with user.js and some other addons is a lot better than any of the forks because theyre always so outdated and have many issues. its not hard to disable all the privacy/security/feature issues which come with firefox

**Comment by CHEF-KOCH** [comment]
The problem about any 'tweaked' and [modded FF](https://en.wikipedia.org/wiki/Category:Web_browsers_based_on_Firefox) is that 
1) like e.g. Pale Mopn (since some versions with different engine) it makes more troubles, e.g. the addons are 'special' imho the effort is not worth to re-write this there is no security benefit.
2) The forks are always behind the real Firefox releases due the fact that Mozilla have simply more developers and a bigger community - which makes any fork more insecure and not more secure.
3) Such modification possible breaks certain aspects, e.g. user.js (just an example)
4) Such projects are mostly hobby projects, and again, it takes more time to merge xyz
5) Modded stuff is mostly hosted on insecure places like one-click hoster due bandwidth reasons
6) To get infected by modded Firefox versions is a lot of easier since you don't have anyhing to compare with (maybe only signatures).

Overall I agree, user.js is the best you can do with the legit and original Firefox. And remember that already some options was getting disabled by default (possible because such tweaks here). SO everyone have the benefit, not only users which needs to download and install untrusted external software.

**Comment by Atavic** [comment]
about:icecat is under _icecat/browser/extensions_ in the package [here](https://ftp.gnu.org/gnu/gnuzilla/38.8.0/).

**Comment by pyllyukko** [comment]
> I am still curious whether Icecat has something more to offer; would an Icecat user please copy-paste the settings found in about:icecat here?

I installed IceCat (45.5.1) and ```about:icecat``` is nowhere to be found. You get the regular "The address isn't valid" error. ```about:home``` does work and is the default homepage, but it only contains a search bar as seen here:

![icecat](https://cloud.githubusercontent.com/assets/1058704/23339055/75ea8a90-fc22-11e6-9325-edbade2371e7.png)

**Comment by pyllyukko** [comment]
Also the [IceCat tour](https://libreplanet.org/wiki/Group:IceCat/Tour) link from the help menu is full of nothing.

**Comment by pyllyukko** [comment]
So it was a dead end. I'm closing this now. Feel free to re-open if the need arises.
