### ISSUE TITLE
user_pref("browser.search.update",		false);

### ISSUE THREAD

**Issue by kaihendry** [pyllyukko/user.js#59]
I see no reference to this preference in https://support.mozilla.org/en-US/kb/how-stop-firefox-making-automatic-connections#w_auto-update-checking

I don't use this preference so I am not sure what the symptoms are in wireshark.

Btw I am "hardening" [1] Firefox over here https://github.com/Webconverger/webc/blob/master/opt/firefox/browser/defaults/preferences/webconverger.js

[1] Hardening means no automatic 3rd party connections for me :grin:

**Comment by CHEF-KOCH** [comment]
This was already discussed and it doesn't have any benefit to disable it, except security problems. Some search engines will anyway use the addons for the search bar which hardly needs updates and the one you can type directly e.g. like google uses own api's which can't be blocked, because it gives a lot of troubles. 


Please so some research and use the search function, I already wrote a lot about the 'connection on startup' thing and explained really everything - the rest can/should anyway enabled/disabled by uBlock an not with user.js because e.g. I want FF sync feature and some people don't.

**Comment by pyllyukko** [comment]
It is the "and uncheck Search Engines." part (in the GUI). That modifies the value of ```browser.search.update```.

**Comment by CHEF-KOCH** [comment]
This Option will be anyway removed with FF 45. Just saying.

**Comment by pyllyukko** [comment]
> This option will be anyway removed with FF 45. Just saying.

Link?

**Comment by CHEF-KOCH** [comment]
Already removed with 48, see [here](http://kb.mozillazine.org/About:config_entries). Maybe earlier just re-looked at the list today and it's removed.

**Comment by pyllyukko** [comment]
> see here

I can't find anything in there that says it's removed. Just:

```
True (default): Automatically check for updates to search plugins.
False: Opposite of the above.
Note: Firefox 1.5 and above only. 
```

**Comment by CHEF-KOCH** [comment]
You're right somehow it's still present in latest stable version. :confused:

**Comment by Roman-Nopantski** [comment]
Might as well close this. I think the q was answered 16 months ago

**Comment by pyllyukko** [comment]
Will do.
