### ISSUE TITLE
uBlock filters setup

### ISSUE THREAD

**Issue by MacProGirl** [pyllyukko/user.js#61]
What setup do you recommend for a non-advanced Mac Firefox user for uBlock? 

Also, if you have other important extensions you recommend, just scream it out. 

I might as well list my current setup:
EasyList‎ 
Peter Lowe’s Ad server list‎
EasyPrivacy‎ 
Malware Domain List‎
Malware domains‎ 
Fanboy’s Annoyance List‎
Dan Pollock’s hosts file‎
hpHosts’ Ad and tracking servers‎ 
Fanboy's Swedish‎ (since I am Swedish)

Thanks a lot!

**Comment by berrythesoftwarecodeprogrammar** [comment]
i dont see any real reason to not select them all (minus the regional ones).
i use:
```
My Filters
uBlock filters
uBlock filters - Badware risks
uBlock filters - Privacy
uBlock filters - Unbreak
Adblock Warning Removal List
Anti-Adblock Killer | Reek
EasyList
Peter Lowe’s Ad server list
Basic tracking list by Disconnect
EasyPrivacy
Fanboy's Enhanced Tracking List
Malvertising filter list by Disconnect
Malware Domains List
Malware domains
Malware domains (long-lived)
Malware filter list by Disconnect
Spam404
Dan Pollock’s hosts file
hpHosts’ Ad and tracking servers
MVPS HOSTS
```
(however many of the hosts file type lists i disabled and use them in uMatrix instead. uMatrix probably isnt what you want as a non-advanced user though, so you can use those lists in uBlock)

and in the custom urls i have:
```
https://raw.githubusercontent.com/metaphoricgiraffe/behind-the-scenes-filters/master/filters.txt
https://easylist-downloads.adblockplus.org/fb_annoyances_sidebar.txt
https://easylist-downloads.adblockplus.org/fb_annoyances_newsfeed.txt
```

**Comment by CHEF-KOCH** [comment]
It makes no sense to use all filters, because if you opening them one by one you will see most or all of them including dublicates (while e.g. Dan Pollock uses most of the ones from hpHosts as an example), this is normal because mostly the filters are for random purchases designed and not for special cases. Only fanboy have for such reasons seperate filters/lists, e.g. his social blocking list, the ultimate list, the YouTube blocking list and and and. 

I prefer instead of load 150k filters into the browser to instead just block all the domains via hosts (works on every OS) and the custom filters which can't be blocked because it would break the entire domain should be loaded by uMatrix/uBlock. Benefit also is that you harden the entire OS not only Browser.

That is the best compromise between Performance, not wasting ressources and of course to use hosts with tools that remove automatically dublicates is more effective compared to load everything and run into problems.

And another problem is that if you visit a lot of different Websites that you possible run into problems, e.g. if an custom filter or language based one uses the same like dan pollock's filter list. You will see in this case on the debug/waterfall screen the two hosts sources and you need to possible adjusting them, the time you need is not worth to handle/manipulate that file manually after each upgrade.

**Comment by berrythesoftwarecodeprogrammar** [comment]
i thought ublock parses and merges the lists so duplicates dont matter

**Comment by CHEF-KOCH** [comment]
Are you sure? Because it would break dynamic filters, for such a reason there is the 'even if' option in case you load something on it and it shows duplicates (you will see two or more blocking lists if you click on it). But maybe this was changed, in this case it still anyway makes no sense because there is no benefit except more ram usage. In fact the Browser never connects to any of this pages which contains possible malware, so as always if you as user are on warez pages which including sub-domains or stuff with tracking things it will connect in this case. But normally you only have he domain, possible the ads and not need to break the entire domain).

**Comment by berrythesoftwarecodeprogrammar** [comment]
seems like i might be wrong about the mergeing since i cant find anything about it, in which case one should probably select fewer but more effective lists. but personally i havent experienced any problems or slow speeds because of my setup. and yeah for the lists which are just host files, theyd be more effective in the OS's hosts file but maintaining that doesnt seem like an activity non advanced users would want to be dealing with.

@MacProGirl your current set up seems fine. you could add more if you think you wont experience a slow browser/computer experience because of it. could help, more likely to be unnecessary overkill.

**Comment by nodiscc** [comment]
uBlock Origin with all lists + 2 regional lists enabled doesn't show excessive memory usage and _very_ rarely breaks sites for me.

Using lists that are in hosts format through your OS hosts file would technically be better (blocked even outside the browser), but this requires merging, updating and managing them through an external tool.

**Comment by CHEF-KOCH** [comment]
Well, the problem is as always user needs. I not recommend such a configuration for normal users. And things getting more worst if you use DNSSEC/Dnscrypt + proxy or vpn because it overrides the list anyway or comes with own list (some vpn providers use an own list). And of course memory and duplicates because as I said + the fact that safe-browsing that we use/enabled also use it's own list. It's just not necessary to do all this. If you believe in myths that this will be secure more stuff you're wrong. Also remember that sites like gmail, facebook often gets updates, so you must always stay on the line, this sound like no problem but not everyone have unlimited bandwidth.  

Of course in case you have 8+ gb ram, high bandwidth you can load and waste million of entries but it's anyway not necessary. 

I personally use my mention method which (as already said) 'secures' the entire OS not only the Browser since apps/software's also comes with ads, e.g. some Windows 10 tiles. So I see no reasons why not load all 'bad' domains into the hosts file and only use the filters which contains special dynamic filters or only ads related stuff. This works very good. 


> Using lists that are in hosts format through your OS hosts file would technically be better (blocked even outside the browser), but this requires merging, updating and managing them through an external tool.

Agreed but e.g. on Windows and even on Linux there a a lot of small tools avbl. for this. But I agree this needs more handling.

**Comment by CHEF-KOCH** [comment]
Btw I don't think that this will mentioned in the Readme or so, because it's up to the user which config he/she prefers. But besides this we may can leave this thread open to common talk about uMatrix/uBlock and filters to avoid additional threads/questions.

**Comment by MacProGirl** [comment]
@CHEF-KOCH 
Host file? That's files that block certain IP addresses from the OS right? Well, that's all I almost know :) Is that something for me on a Mac? Is my computer even so susceptible to problem while browsing? Is there a tool for this? Would I know what sites to block? I really want something that's easy so problem solving won't be a problem.

@all other
Thanks!

**Comment by pyllyukko** [comment]
> Is my computer even so susceptible to problem while browsing?

Yes it is.

**Comment by MacProGirl** [comment]
@pyllyukko I added Avira antivirus two days ago. I hope that helps. And I am trying out uBlock. But it I don't get some good answers here about how to set it up, I might as well go back Ghostery which seems very easy to use and understand. And I haven't got any indications that Ghostery might be much worse for my future online security.

Thanks!

**Comment by nodiscc** [comment]
This thread is confusing. How to set up ublock: 1) [Install uBlock origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/). 2) Go to uBlock's preferences > Filter Lists 3) Enable all lists that you think are relevant (personally I enable them all, except regional lists where I only enable them for my region). 4) Save. Done

**Comment by MacProGirl** [comment]
@nodiscc  If it only was that easy as you stated... I don't see that we have a consensus here for using ALL lists. People have different opinions on that. 

Addition info about where to find info about setting up you host file would be appreciated. 

I copied @berrythesoftwarecodeprogrammar list. He has all besides:
- EasyList without element hiding rules‎
- Anti-Thirdparty Social
- Fanboy’s Social Blocking List‎ 
- Fanboy+Easylist-Merged Ultimate List‎ 

And he doesn't have Fanboy’s Annoyance List‎ which I have. Why is that?

Also I wonder what the customs urls are and how to find something to put there?

Thanks again all!

**Comment by MacProGirl** [comment]
Related question, should I check "Block Harmful Sites" and "Block Phishing Sites" in Firefox when I have uBlock or will that only take up unnecessary resources?

**Comment by nodiscc** [comment]
> And he doesn't have Fanboy’s Annoyance List‎ which I have. Why is that?

You have to read each list's description, and review it's contents, (10000s of entries), and decide for yourself. Eg do some research and decide for yourself if you need [Fanboy's annoyances list](https://www.fanboy.co.nz/):

>Fanboy Annoyances List
> In page Pop-Ups and other annoyances; thereby substantially decreasing web page loading times and uncluttering them (includes Fanboy-Social List.)

 * This full list can be reviewed here: https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
 * You _should_ do this research for _every_ list, and decide whether or not you want it enabled. You _should_ also review all updates of the list every day.
 * Or if you don't have the time for this (I don't), enable lists that _look_ useful by their name/short description
 * Or if you don't have time for this, enable all lists (which is what I do)
 * Or if you don't have time, leave the defaults enabled.

Like many things in computing, it all comes down to _who/what you trust_. _I_ trust maintainers to provide good lists, but it is a personal matter, so that's why there can be no consensus on enabling all lists,1, 4, 5 or none. Worst case, you slightly increase memory/CPU usage for no added benefit, worst worst case you enable lists that filter items you _don't_ want to filter (eg. annoyances list even filters things like RSS icons, some visual effects... read the list), and worst worst worst case it gives you a false sense of security (lists can never be fully up to date with tracking methods, ad blockers cover only a tiny aspect of security/privacy)

> Also I wonder what the customs urls are and how to find something to put there?

Refer to the uBlock documentation/support.

> should I check "Block Harmful Sites" and "Block Phishing Sites"

Decide for yourself. Read more about Firefox malware blocking here https://github.com/pyllyukko/user.js/blob/master/user.js#L223. These lists are from Google and differ from uBlock lists, but there is certainly overlap between them. It _will_ take up unnecessary resources. On a semi-modern computer the performance difference is not significant.

**Comment by berrythesoftwarecodeprogrammar** [comment]
good answer from nodiscc.

@MacProGirl: ublock is definitely more effective than ghostery etc and i think its easy to use. just select lists (or use the defaults? i dont remember what the default settings are) and youre done. if it sounds like it blocks bad stuff it probably does. malware, tracking, annoyances

if you're using pyllyukko's user.js then the options for blocking harmful sites and phishing sites is probably enabled already. i personally turn off all of firefox's anti-malware and anti-tracking features and just rely on the blocklists in ublock so that i dont have multiple things checking urls, only ublock. and one of the disconnect lists in ublock is meant to be the same as mozillas tracking feature. and there are multiple malware lists in ublock which would probably make a better replacement for the firefox features, some of which can leak information to google etc.

**Comment by CHEF-KOCH** [comment]
@ MacProGirl  

* [Edit Your Mac Hosts File with Text Edit](http://www.tekrevue.com/tip/edit-hosts-file-mac-os-x/) [and another one](http://decoding.wordpress.com/2009/04/06/how-to-edit-the-hosts-file-in-mac-os-x-leopard/)
* [Hosts file Explanation from Wikipedia](https://en.wikipedia.org/wiki/Hosts_file)
* [Update example via Shell on Mac](http://gigliwood.com/blog/auto-update-your-hosts-file.html)
* On Windows there exists HostMan, Host Editor and such Tools I think such Tools avbl. on all OS to easily block malware Domains. Even Android have e.g. AdGuard or AdAway, I'm not sure because I'm not that Mac OS user but if you can't any tool to automatically update Hosts file on Mac AdGuard works on almost every device and OS.

> Related question, should I check "Block Harmful Sites" and "Block Phishing Sites" in Firefox when I have uBlock or will that only take up unnecessary resources?

Yes I already explained it, with safe-browsing and other mechanism enabled + hosts you normally need only load in uBlock/uMatrix to block the ads and nothing more it's wasting ressources, can lead in troubles and doesn't secure more. 
In fact if you use an Antivirus/Proxy/VPN it also Plays an important role because they alreay mostly are come with traffic Scanners, pishing protection, own addons/plugins and many more.

**Comment by berrythesoftwarecodeprogrammar** [comment]
spybot search & destroy 1.6.2 is very good too. its immunization feature adds spyware related hosts to your hosts file and browser blacklists and definitions are updated regularly http://filehippo.com/download_spybot_search_destroy/5168/

**Comment by CHEF-KOCH** [comment]
Bad news for all adblock users, some pages are gonna to know to admonish some operators/filter creators because they saying it e.g. can bypass xyz (also encryption). 

So I recommend to not post any filter list over here anymore or just directly link them only. 

I only have a german source but I'm quite sure more will be warned very soon, so this is only the beginning to fight against the blockers. 

* http://www.golem.de/news/werbeblockersperre-eyeo-loescht-filterbefehle-aus-dem-adblock-forum-1510-117094.html
* https://adblockplus.org/forum/viewtopic.php?f=2&t=41068

So be careful, GitHub is also known to 'delete' stuff immediately so censorship everywhere.

**Comment by MacProGirl** [comment]
@nodiscc 
_"Refer to the uBlock documentation/support."_
- I haven't found any good documentations. I tried the website and I tried Google.

I unchecked Firefox Malware and Phishing warnings as @berrythesoftwarecodeprogrammar and @CHEF-KOCH has suggested. I installed most uBlock filters as suggested. I installed NoScript (it's giving me some headache to begin with, but hopefully that resolves). I start using Avira Free virus scanner on my Mac. 

I am saving the HOSTS file urls @CHEF-KOCH provided for future reference if I think I will need that additional safety filter. I should most often be able to browse safely without it I hope? Also I didn't understand what you meant hear: _"The author of uBlock also not use e.g. dan pollock's file because from what I could understand he uses the same method like me."_ What is the method you use that is redundant with some list of Dan Pollock's?

@All 
Thanks for taking all your precious time to help with these questions! So far it's been of much help. Very much appreciated! Thanks KOCH for warning us about posting filter lists.

**Comment by CHEF-KOCH** [comment]
Dan Pollock's list is known to be problematically under some cases and you better use instead another one like Cameleon. Because the mentioned on is very strict and you possible need to exclude some domains, some are also already comment out because such troubles. And often some tools/addons have problems to parse comments or excluding them because of wrong implementation. In some cases it's also possible that it will be removed and you get the mentioned problems too. 

My intent was just to say that you not need everything, as said it makes not that really much sense except possible troubles and wasting time to figure it out. 

Btw you not need to mention me I always subscribe my thread's I'm talking in to see the discussion processes.

**Comment by nodiscc** [comment]
Hi, I wanted to share a simple way to restrict cross-site requests using uBlock origin. It took me some time to figure out (after from moving from RequestPolicy+uBlock to only µB.) I have documented it [here](https://github.com/RequestPolicyContinued/requestpolicy/wiki/FAQ#using-ublock-like-requestpolicy).

The basics of it is to define a `Block` rule for all third-party resources:

![](https://cloud.githubusercontent.com/assets/3950390/11353760/68a6566c-9246-11e5-99b6-030f7e1205c6.png).

This simplifies my workflow a lot as I only have to do whitelisting in **1** addon.

**Comment by CHEF-KOCH** [comment]
It's isn't necessary to disable 3rd-party since NoScript do a better job, this is only necessary if you not use any extensions/plugins like flash, silverlight (and then you can uninstall NoScript because this is what uBlock simply is not designed for - see in issue tracker 'NoScript and uBlock difference')'. 

I Highly recommend [this setup](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode) because you can simply switch to a lower mode if you getting troubles.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
In case it hasn't been mentioned, uBlock will not use redundant entries in filters should a prior filter active before it have the same entry. (This is why there is a count on each that displays how many filters are actually being used on the list once activated.)

**Comment by publicarray** [comment]
>There are nice virtuous side effects with using compiled filter lists. One of them is the very accurate counting of distinct filters, and the ability to completely detect duplicates. Prior to 0.8.9.0, µBlock tried best to detect duplicate, but it wasn't perfect, as it was using the raw representation of a filter to decide whether the filter was already processed.

source: https://github.com/gorhill/uBlock/wiki/Launch-and-filter-lists-load-performance

**Comment by CHEF-KOCH** [comment]
We don't need to talk about it, it's logically:
* More stuff to load -> more footprints because it needs to handled by ram 
* More != (is not) better but can cause several troubles like in the past (just watch it's issue tracker)
* Remember if you use another DNS it could be bypassed anyway (so ensure the domains in your router/host are parsed)
* Less is really more, [please look at this project](https://github.com/rocketshipapps/adblockfast) what I mean 7 rules while others need 49k+ and does the same ... that's what I call impressive/resource friendly

**Comment by publicarray** [comment]
I'm sorry to say that that is a matter of personal opinion. If I want to change a setting from the default I need to add a line for that preference. I have a few personalised settings that I have added to my user.js so they are the same when I reinstall my machine or I create a new FF profile. Now that I have added a few more lines to my file is it now less valuable?

How is the DNS server you use relevant in the Firefox config? I have changed my DNS and I'm running unbound locally. This OS stuff.

**Comment by CHEF-KOCH** [comment]
Yes because it's OS stuff most people not often look at this and malware could simply change your DNS (okay more or less simple) but's possible like in the past. Then all of the domain blocking stuff will be obsolete, I don't know if that was mentioned in uBlock/uMatrix but's a fact. So I was just saying.

> Now that I have added a few more lines to my file is it now less valuable?

Sorry, it seems you misunderstand me, I mean loading 'million' of domains into it, which uBlock means to sort out, and this will coast performance/memory that's for sure no matter what someone want to tell me. I in general see no problem if the user add 'a few' lines into it e.g. because the dynamic filter maybe miss some new things (because youtube and other big pages often change something).

**Comment by publicarray** [comment]
I apologise I responded to the wrong issue...

**Comment by CHEF-KOCH** [comment]
Maybe we can close this, because it's optional and almost every question is explained/answered with it's wiki. The rest is matter of taste. :8ball:

**Comment by pyllyukko** [comment]
> Maybe we can close this

Yep.
