### ISSUE TITLE
possible additions related to telemetry and datareporting

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [pyllyukko/user.js#63]
toolkit.telemetry.unified -> false
toolkit.telemetry.unifiedIsOptIn -> true
toolkit.telemetry.archive.enabled -> false  `i looked in my profile folder and found that it was storing things in a folder called /saved-telemetry-pings/`
toolkit.telemetry.server -> ""
experiments.manifest.uri -> ""
toolkit.telemetry.cachedClientID -> ""
datareporting.policy.dataSubmissionEnabled -> false
datareporting.healthreport.pendingDeleteRemoteData -> false
datareporting.sessions.currentIndex -> 0 `or "0"? in one of my firefox's its a string and in one its an integer lol`
datareporting.sessions.prunedIndex -> 0
experiments.enabled -> false
experiments.supported -> false

sources:
https://gecko.readthedocs.org/en/latest/toolkit/components/telemetry/telemetry/preferences.html
https://wiki.mozilla.org/QA/Telemetry/AboutPreferences
my about:config

you might wanna search your about:config for 'datareporting' and 'telemetry'. mine had a lot of weird datareporting session things saved which i removed. also check the /datareporting/ folder in your profile folder. it seems to be recreated and files written even when these features are disabled? i added them to ccleaner and also the /saved-telemetry-pings/ folder. its worth it checking your profile folder for unnecessary/weird files and folders if your profile is as old as mine.

**Comment by CHEF-KOCH** [comment]
The problem about that is, you not need to configure every single switch. For example if you just 'kill' all about:config stuff with url's in it (except sync if you really need it) you can leave everything enabled. So, we must find a proper way to handle stuff with as less effort as possible without breaking the security aspect.

Another example, killing the clientID is useless if you anyway disabled the entire option so you don't need to touch this. In fact if you touch all options it can make your life a lot of more complicated because you need maybe on xyz update to reset all the about:config stuff you changed to see if it was removed or not. In this case I already created a pull request with an link wich shows the diff between each FF release. Maybe we also need something like this because as I said in the addons thread, there is no possability (besides to reset the entire profile) that you can only reset all about:config things or only this which was really getting removed.

But I will grab your stuff and see what I can do.

**Comment by CHEF-KOCH** [comment]
Btw I already asked Mozilla to change the about:config 'resetting' problem but without any answer. Maybe someone with a Bugzilla account can open another thread about it (lost my acount/password, sr). Because I still think that this is a huge Problem which never was 'fixed'.

**Comment by berrythesoftwarecodeprogrammar** [comment]
yeah, those are just things i did, some was to clean up my own profile. i just wrote about all of it so you more experienced users can figure out which ones should be put in to user.js because i think some of those prefs might be useful

**Comment by pyllyukko** [comment]
Ok, so I set ```toolkit.telemetry.unified``` to ```false```. I think that should be enough.

The gecko link states that "```toolkit.telemetry.enabled```: If ```unified``` is off, this controls whether the Telemetry module is enabled."

**Comment by pyllyukko** [comment]
I'm closing this now, as setting ```.unified``` and ```.enabled``` should kill the whole telemetry system. Re-open this if you disagree or have some other additional info.

BTW. As @CHEF-KOCH said, there's no point in setting every single setting (which is a lot!) that somehow relates to some feature, but only the "main switches".

So as an analogy: if I want silence and I power off my amplifier, there's no need to touch the volume control anymore, as it's not powered on anymore and there's no sound anyway.

**Comment by berrythesoftwarecodeprogrammar** [comment]
are the experiments and datareporting values taken care of already too?

**Comment by pyllyukko** [comment]
Well at least health reporting should be. Experiments is not set. I will check this...

**Comment by CHEF-KOCH** [comment]
I think we can lose it.

> datareporting.sessions.currentIndex
> toolkit.telemetry.cachedClientID
> datareporting.policy.dataSubmissionEnabled
> datareporting.healthreport.pendingDeleteRemoteData
> datareporting.sessions.currentIndex
> datareporting.sessions.prunedIndex

Not exists anymore. So reset it. 


> toolkit.telemetry.unifiedIsOptIn -> true

Why you want to enable it, it's false default and we not need to change it. 


> toolkit.telemetry.unified 

It's default true and we can leave it, because we entirely removed any telemetry so we not need to touch it.

> toolkit.telemetry.server ""

Nope. You can enable all option and remove all urls or disable it and leave everything else untouched, we use the last method.

**Comment by pyllyukko** [comment]
> are the experiments and datareporting values taken care of already too?

Well now they should be dealt with, so I'll close this (again).

**Comment by pyllyukko** [comment]
> toolkit.telemetry.unified
> 
> It's default true and we can leave it, because we entirely removed any telemetry so we not need to touch it.

Well actually... according to the links provided by @berrythesoftwarecodeprogrammar, it seemed that setting only ```toolkit.telemetry.enabled``` was not enough.
